import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
import joblib
from sklearn.decomposition import TruncatedSVD


# Глобальный, сбалансированный датасет
data = [
    ['math', 'f(x) = ax^2 + bx + c', 'функция уравнение корень значение'],
    ['math', '\\sum_{i=1}^n x_i', 'сумма индекс предел итерация'],
    ['math', '\\int_a^b f(x) dx', 'интеграл площадь вычисление'],
    ['math', 'P(A) = m/n', 'вероятность событие статистика'],
    ['math', '\\sin \\alpha + \\cos \\beta', 'тригонометрия угол функция'],
    ['math', 'A \\cdot B = C', 'матрица вектор умножение'],
    ['math', '\\lim_{n \\to \\infty}', 'предел бесконечность последовательность'],
    ['math', '\\frac{dy}{dx}', 'производная дифференциал функция'],
    ['math', 'C_3 = C + \\frac{\\mathrm{Mn}}{6} + \\frac{\\mathrm{Cr} + \\mathrm{Mo} + \\mathrm{V} + \\mathrm{Ti} + \\mathrm{Nb}}{5} + \\frac{\\mathrm{Cu} + \\mathrm{Ni}}{15} + 5B', 'углеродный эквивалент'],
    ['math', 'P_{cr} = C + \\frac{\\mathrm{Si}}{30} + \\frac{\\mathrm{Mn} + \\mathrm{Cu} + \\mathrm{Cr}}{20} \\frac{\\mathrm{Mo}}{15} + \\frac{\\mathrm{Ni}}{60} + \\frac{\\mathrm{V}}{10} + 5B', 'углеродный эквивалент'],
    ['math', 'C_{\\mathrm{крн}}, \\% = \\frac{\\Delta\\sigma_p/\\sigma_p^0 + \\Delta\\sigma_{от}/\\sigma_{от}^0 + \\Delta f/f^0 + \\Delta A_2/A_2^0}{4}', 'интегральный показатель склонности'],
    ['math', 'ES = D_{\\max}-D ; EI = D_{\\min}-D ; es = d_{\\max}-d ; ei = d_{\\min}-d', 'предельные отклонения отверстия и вала'],
    ['math', 'ES = D_{\\max} - D ; EI = D_{\\min} - D ; es = d_{\\max} - d ; ei = d_{\\min} - d', 'предельные отклонения посадка'],
    ['math', 'S_{\\max} = D_{\\max} - d_{\\min} - ES - ei', 'посадка с зазором максимальный зазор'],
    ['math', 'N_{\\max} = d_{\\max} - D_{\\min} - es - EI', 'посадка с натягом максимальный натяг'],
    ['math', 'T_N = N_{\\max} - N_{\\min} = (es - EI) - (ei - ES) = T_D + T_d', 'допуск посадки'],
    ['math', 'a_w = (d_{w2} \\pm d_{w1}) / 2 ; u = \\omega_1 / \\omega_2 = d_{w2} / d_{w1}', 'межосевое расстояние передаточное число'],
    ['math', 'W_p = \\frac{\\pi D^3}{16}', 'момент сопротивления при кручении (круг)'],
    ['math', 'J_x = \\int_A y^2 \\, dA', 'осевой момент инерции'],
    ['math', 'J_p = \\int_A \\rho^2 \\, dA', 'полярный момент инерции'],
    ['math', '(a + b)^2 = a^2 + 2ab + b^2', 'квадрат суммы формула сокращённого умножения'],
    ['math', '(a - b)^2 = a^2 - 2ab + b^2', 'квадрат разности формула сокращённого умножения'],
    ['math', 'a^2 - b^2 = (a - b)(a + b)', 'разность квадратов формула сокращённого умножения'],
    ['math', '(a + b)^3 = a^3 + 3a^2b + 3ab^2 + b^3', 'куб суммы формула сокращённого умножения'],
    ['math', '(a - b)^3 = a^3 - 3a^2b + 3ab^2 - b^3', 'куб разности формула сокращённого умножения'],
    ['math', 'a^3 + b^3 = (a + b)(a^2 - ab + b^2)', 'сумма кубов формула сокращённого умножения'],
    ['math', 'a^3 - b^3 = (a - b)(a^2 + ab + b^2)', 'разность кубов формула сокращённого умножения'],
    ['math', '\\frac{a}{b} + \\frac{c}{d} = \\frac{ad + bc}{bd}', 'сложение дробей общий знаменатель'],
    ['math', '\\frac{a}{b} \\cdot \\frac{c}{d} = \\frac{ac}{bd}', 'умножение дробей'],
    ['math', '\\left(\\frac{a}{b}\\right)^n = \\frac{a^n}{b^n}', 'степень дроби'],
    ['math', 'a^m \\cdot a^n = a^{m+n}', 'произведение степеней с одинаковым основанием'],
    ['math', '\\frac{a^m}{a^n} = a^{m-n}', 'частное степеней с одинаковым основанием'],
    ['math', '(a^m)^n = a^{mn}', 'возведение степени в степень'],
    ['math', '(ab)^n = a^n b^n', 'степень произведения'],
    ['math', 'a^{-n} = \\frac{1}{a^n}', 'отрицательная степень'],
    ['math', 'a^{1/n} = \\sqrt[n]{a}', 'дробная степень корень'],
    ['math', '\\sqrt[n]{ab} = \\sqrt[n]{a} \\cdot \\sqrt[n]{b}', 'корень из произведения'],
    ['math', '\\sqrt[n]{\\frac{a}{b}} = \\frac{\\sqrt[n]{a}}{\\sqrt[n]{b}}', 'корень из частного'],
    ['math', '(\\sqrt[n]{a})^m = \\sqrt[n]{a^m}', 'степень корня'],
    ['math', '\\sqrt[m]{\\sqrt[n]{a}} = \\sqrt[mn]{a}', 'корень из корня'],
    ['math', '\\log_a(xy) = \\log_a x + \\log_a y', 'логарифм произведения сумма логарифмов'],
    ['math', '\\log_a\\left(\\frac{x}{y}\\right) = \\log_a x - \\log_a y', 'логарифм частного разность логарифмов'],
    ['math', '\\log_a(x^p) = p \\log_a x', 'логарифм степени'],
    ['math', '\\log_a 1 = 0', 'логарифм единицы'],
    ['math', '\\log_a a = 1', 'логарифм основания'],
    ['math', 'a^{\\log_a x} = x', 'основное логарифмическое тождество'],
    ['math', '\\log_a x = \\frac{\\log_b x}{\\log_b a}', 'переход к новому основанию логарифма'],
    ['math', '\\ln x = \\log_e x', 'натуральный логарифм основание непера'],
    ['math', '\\lg x = \\log_{10} x', 'десятичный логарифм'],
    ['math', '\\tan x = \\frac{\\sin x}{\\cos x}', 'тангенс через синус и косинус'],
    ['math', '\\cot x = \\frac{\\cos x}{\\sin x} = \\frac{1}{\\tan x}', 'котангенс через синус и косинус'],
    ['math', '\\sec x = \\frac{1}{\\cos x}', 'секанс'],
    ['math', '\\csc x = \\frac{1}{\\sin x}', 'косеканс'],
    ['math', '\\sin(\\alpha \\pm \\beta) = \\sin\\alpha \\cos\\beta \\pm \\cos\\alpha \\sin\\beta', 'синус суммы и разности'],
    ['math', '\\cos(\\alpha \\pm \\beta) = \\cos\\alpha \\cos\\beta \\mp \\sin\\alpha \\sin\\beta', 'косинус суммы и разности'],
    ['math', '\\tan(\\alpha \\pm \\beta) = \\frac{\\tan\\alpha \\pm \\tan\\beta}{1 \\mp \\tan\\alpha \\tan\\beta}', 'тангенс суммы и разности'],
    ['math', '\\sin(2\\alpha) = 2\\sin\\alpha \\cos\\alpha', 'синус двойного угла'],
    ['math', '\\cos(2\\alpha) = \\cos^2\\alpha - \\sin^2\\alpha = 2\\cos^2\\alpha - 1 = 1 - 2\\sin^2\\alpha', 'косинус двойного угла'],
    ['math', '\\tan(2\\alpha) = \\frac{2\\tan\\alpha}{1 - \\tan^2\\alpha}', 'тангенс двойного угла'],
    ['math', '\\sin\\frac{\\alpha}{2} = \\pm \\sqrt{\\frac{1 - \\cos\\alpha}{2}}', 'синус половинного угла'],
    ['math', '\\cos\\frac{\\alpha}{2} = \\pm \\sqrt{\\frac{1 + \\cos\\alpha}{2}}', 'косинус половинного угла'],
    ['math', '\\sin\\alpha + \\sin\\beta = 2\\sin\\frac{\\alpha+\\beta}{2}\\cos\\frac{\\alpha-\\beta}{2}', 'сумма синусов'],
    ['math', '\\sin\\alpha - \\sin\\beta = 2\\cos\\frac{\\alpha+\\beta}{2}\\sin\\frac{\\alpha-\\beta}{2}', 'разность синусов'],
    ['math', '\\cos\\alpha + \\cos\\beta = 2\\cos\\frac{\\alpha+\\beta}{2}\\cos\\frac{\\alpha-\\beta}{2}', 'сумма косинусов'],
    ['math', '\\cos\\alpha - \\cos\\beta = -2\\sin\\frac{\\alpha+\\beta}{2}\\sin\\frac{\\alpha-\\beta}{2}', 'разность косинусов'],
    ['math', '\\sin\\alpha \\cos\\beta = \\frac{1}{2}[\\sin(\\alpha+\\beta) + \\sin(\\alpha-\\beta)]', 'произведение синуса на косинус'],
    ['math', '\\cos\\alpha \\cos\\beta = \\frac{1}{2}[\\cos(\\alpha+\\beta) + \\cos(\\alpha-\\beta)]', 'произведение косинусов'],
    ['math', '\\sin\\alpha \\sin\\beta = \\frac{1}{2}[\\cos(\\alpha-\\beta) - \\cos(\\alpha+\\beta)]', 'произведение синусов'],
    ['math', '\\frac{d}{dx}(c) = 0', 'производная константы'],
    ['math', '\\frac{d}{dx}(x^n) = nx^{n-1}', 'производная степенной функции'],
    ['math', '\\frac{d}{dx}(\\sin x) = \\cos x', 'производная синуса'],
    ['math', '\\frac{d}{dx}(\\cos x) = -\\sin x', 'производная косинуса'],
    ['math', '\\frac{d}{dx}(\\tan x) = \\sec^2 x', 'производная тангенса'],
    ['math', '\\frac{d}{dx}(\\cot x) = -\\csc^2 x', 'производная котангенса'],
    ['math', '\\frac{d}{dx}(\\ln x) = \\frac{1}{x}', 'производная натурального логарифма'],
    ['math', '\\frac{d}{dx}(\\log_a x) = \\frac{1}{x \\ln a}', 'производная логарифма по основанию a'],
    ['math', '\\frac{d}{dx}(e^x) = e^x', 'производная экспоненты'],
    ['math', '\\frac{d}{dx}(a^x) = a^x \\ln a', 'производная показательной функции'],
    ['math', '\\int x^n dx = \\frac{x^{n+1}}{n+1} + C,\\ n \\neq -1', 'интеграл степенной функции'],
    ['math', '\\int \\frac{1}{x} dx = \\ln|x| + C', 'интеграл гиперболы'],
    ['math', '\\int e^x dx = e^x + C', 'интеграл экспоненты'],
    ['math', '\\int a^x dx = \\frac{a^x}{\\ln a} + C', 'интеграл показательной функции'],
    ['math', '\\int \\sin x \\, dx = -\\cos x + C', 'интеграл синуса'],
    ['math', '\\int \\cos x \\, dx = \\sin x + C', 'интеграл косинуса'],
    ['math', '\\int \\tan x \\, dx = -\\ln|\\cos x| + C', 'интеграл тангенса'],
    ['math', '\\int \\cot x \\, dx = \\ln|\\sin x| + C', 'интеграл котангенса'],
    ['math', '\\int \\frac{dx}{\\sqrt{1-x^2}} = \\arcsin x + C', 'интеграл арксинус'],
    ['math', '\\int \\frac{dx}{1+x^2} = \\arctan x + C', 'интеграл арктангенс'],
    ['math', '\\int u \\, dv = uv - \\int v \\, du', 'интегрирование по частям'],
    ['math', '\\lim_{x \\to 0} \\frac{\\sin x}{x} = 1', 'первый замечательный предел'],
    ['math', '\\lim_{x \\to \\infty} \\left(1 + \\frac{1}{x}\\right)^x = e', 'второй замечательный предел'],
    ['math', '\\lim_{x \\to 0} (1 + x)^{1/x} = e', 'второй замечательный предел альтернативный'],
    ['math', '\\lim_{x \\to 0} \\frac{e^x - 1}{x} = 1', 'предел с экспонентой'],
    ['math', '\\lim_{x \\to 0} \\frac{\\ln(1+x)}{x} = 1', 'предел с логарифмом'],
    ['math', '\\sum_{k=1}^n k = \\frac{n(n+1)}{2}', 'сумма натуральных чисел арифметический ряд'],
    ['math', '\\sum_{k=1}^n k^2 = \\frac{n(n+1)(2n+1)}{6}', 'сумма квадратов натуральных чисел'],
    ['math', '\\sum_{k=1}^n k^3 = \\left(\\frac{n(n+1)}{2}\\right)^2', 'сумма кубов натуральных чисел'],
    ['math', '\\sum_{k=0}^\\infty ar^k = \\frac{a}{1-r},\\ |r|<1', 'сумма бесконечной геометрической прогрессии'],
    ['math', '\\sum_{k=1}^n a_1 r^{k-1} = a_1\\frac{1-r^n}{1-r},\\ r \\neq 1', 'сумма конечной геометрической прогрессии'],
    ['math', '\\sum_{k=1}^\\infty \\frac{1}{k^p} \\text{ сходится при } p>1', 'условие сходимости ряда дирихле'],
    ['math', 'P_n = n!', 'число перестановок факториал'],
    ['math', 'A_n^k = \\frac{n!}{(n-k)!}', 'число размещений без повторений'],
    ['math', 'C_n^k = \\frac{n!}{k!(n-k)!} = \\binom{n}{k}', 'число сочетаний биномиальный коэффициент'],
    ['math', 'C_n^k = C_n^{n-k}', 'свойство симметрии сочетаний'],
    ['math', 'C_n^k = C_{n-1}^{k-1} + C_{n-1}^k', 'рекуррентное соотношение треугольника паскаля'],
    ['math', '(x + y)^n = \\sum_{k=0}^n \\binom{n}{k} x^{n-k} y^k', 'бином ньютона'],
    ['math', '\\sum_{k=0}^n \\binom{n}{k} = 2^n', 'сумма биномиальных коэффициентов'],
    ['math', '\\mathbf{a} \\cdot \\mathbf{b} = a_x b_x + a_y b_y + a_z b_z', 'скалярное произведение в координатной форме'],
    ['math', '\\mathbf{a} \\times \\mathbf{b} = \\begin{vmatrix} \\mathbf{i} & \\mathbf{j} & \\mathbf{k} \\\\ a_x & a_y & a_z \\\\ b_x & b_y & b_z \\end{vmatrix}', 'векторное произведение через определитель'],
    ['math', '|\\mathbf{a}| = \\sqrt{a_x^2 + a_y^2 + a_z^2}', 'длина вектора модуль'],
    ['math', '\\cos \\theta = \\frac{\\mathbf{a} \\cdot \\mathbf{b}}{|\\mathbf{a}| |\\mathbf{b}|}', 'косинус угла между векторами'],
    ['math', '(\\mathbf{a} \\times \\mathbf{b}) \\cdot \\mathbf{c} = \\mathbf{a} \\cdot (\\mathbf{b} \\times \\mathbf{c})', 'смешанное произведение векторов'],
    ['math', '\\frac{dy}{dx} = k y', 'дифференциальное уравнение экспоненциального роста'],
    ['math', 'y = Ce^{kx}', 'решение дифференциального уравнения экспоненциального роста'],
    ['math', '\\frac{d^2y}{dx^2} + \\omega^2 y = 0', 'дифференциальное уравнение гармонического осциллятора'],
    ['math', 'y = A\\cos(\\omega x) + B\\sin(\\omega x)', 'общее решение гармонического осциллятора'],
    ['math', '\\frac{dN}{dt} = rN\\left(1 - \\frac{N}{K}\\right)', 'логистическое уравнение фергюльста'],
    ['math', '(x - a)^2 + (y - b)^2 = R^2', 'уравнение окружности центр радиус'],
    ['math', '\\frac{x^2}{a^2} + \\frac{y^2}{b^2} = 1', 'уравнение эллипса'],
    ['math', '\\frac{x^2}{a^2} - \\frac{y^2}{b^2} = 1', 'уравнение гиперболы'],
    ['math', 'y^2 = 2px', 'уравнение параболы'],
    ['physics', '\\sigma = E \\varepsilon', 'напряжение деформация закон упругость'],
    ['physics', 'F = m a', 'сила масса ускорение динамика'],
    ['physics', 'Q = mc\\Delta T', 'теплота энергия нагрев температура'],
    ['physics', 'P = IV', 'ток мощность напряжение электричество'],
    ['physics', '\\rho = m/V', 'плотность объем масса'],
    ['physics', '\\tau = \\eta \\frac{dv}{dx}', 'вязкость течение трение скорость'],
    ['physics', 'E = mc^2', 'энергия масса скорость света'],
    ['physics', 'F', 'сила приложенная модуль вектор'],
    ['physics', 'V', 'объем скорость потенциал вольт'],
    ['physics', 'P', 'давление мощность импульс'],
    ['physics', 'H', 'напряженность магнитного поля'],
    ['physics', 'T', 'температура период сила натяжения'],
    ['physics', '\\Psi = \\sum_{i=1}^n \\Psi_i^\\Lambda < 1', 'поврежденность трещина Колмогорова'],
    ['physics', '\\psi = G\\left(\\sum_{i=1}^n \\psi_i\\right)^\\alpha; \\psi_i = 1 - \\left(1 - \\int_0^t \\frac{H d\\tau}{\\Lambda_P}\\right)^{\\frac{1}{\\beta+1}}', 'поврежденность трещина Колмогорова'],
    ['physics', 'E = 2 \\lim_{\\Delta l \\to 0} \\sum A_{yd} \\cdot V_{пл.деф} = \\frac{2}{t} \\int_0^l A_{yd}(l) \\cdot S(l) \\, dl', 'энергия трещина разрушение вязкость'],
    ['physics', 'T_{50} = 0{,}454 \\sigma_B P', 'вязкость фосфор прочность структура'],
    ['physics', '\\Delta KCV^{max} = -0{,}257 \\sigma_B - 374 P', 'вязкость фосфор разрушение'],
    ['physics', '\\Delta KCV^{max} = -0{,}208 \\sigma_B - 2440{,}8 S', 'вязкость сера разрушение'],
    ['physics', '\\varepsilon_u = 0{,}27 - 0{,}016[\\mathrm{P}] - 0{,}015[\\mathrm{Mn}] - 0{,}04[\\mathrm{Sn}] - 0{,}04[\\mathrm{Si}] - 1{,}1[\\mathrm{N}]', 'равномерное удлинение легирование'],
    ['physics', '\\Delta T_{50} = -151{,}8 \\Sigma L/A', 'хладноломкость расщепление излом'],
    ['physics', 'K_x = \\frac{\\mathrm{Si}}{30} + \\frac{\\mathrm{Mn} + \\mathrm{Cu} + \\mathrm{Cr}}{20} + \\frac{\\mathrm{Mo}}{15} + \\frac{\\mathrm{Ni}}{60} + \\frac{\\mathrm{V}}{10}', 'легирование феррито-бейнит структура'],
    ['physics', '\\beta_\\sigma = \\frac{\\sigma_p - \\sigma_r}{\\sigma_p}', 'эффект Баушингера напряжение'],
    ['physics', '\\sigma_T k_y d^{-1/2} = \\beta G \\gamma', 'Холл-Петч зерно упрочнение'],
    ['physics', '\\beta T_{xp} = \\ln\\beta - \\ln C - \\ln d^{-1/2}', 'температура хрупкости зерно'],
    ['physics', '\\Delta T_{xp} = -A d^{-1/2}', 'температура хрупкости зерно'],
    ['physics', 'KCV^{max} = 449{,}2 - 15{,}1 d^{-1/2}', 'вязкость размер зерна'],
    ['physics', '\\sigma_{0{,}2} = 0{,}1 + 0{,}6 d^{-1/2}', 'предел текучести зерно'],
    ['physics', 'D^2 - D_0^2 = k t', 'рост зерна аустенит диффузия'],
    ['physics', '\\frac{D(D_t)}{Dt} = M\\left(2\\sigma V / R - G_{pin}\\right),\\quad G_{pin} = 3\\sigma V f / 2r', 'рост зерна частицы Зенера'],
    ['physics', '\\ln(X_P^X) = (G_{mc} - G_m - G_0)/RT = A - B/T', 'равновесие карбид термодинамика'],
    ['physics', 'r_c = 6R / \\pi (3/2 - 2/Z)^{-1}', 'критический радиус частицы'],
    ['physics', 'Z = \\dot{\\varepsilon} \\exp(Q/RT)', 'параметр Зенера-Холломона'],
    ['physics', 'D_{dr} = 22600 Z^{-0{,}27}', 'динамическая рекристаллизация'],
    ['physics', '\\varepsilon_p = K D^{1/2} Z^{0{,}15}', 'пластическая деформация рекристаллизация'],
    ['physics', 'X = 1 - \\exp(-k t^n)', 'рекристаллизация Аврами'],
    ['physics', 't_{0{,}5} = A \\varepsilon^m d_0^p Z^q \\exp(Q/RT)', 'время 50% рекристаллизации'],
    ['physics', 'D_r = B \\varepsilon^c Z^d D_0^e', 'размер рекристаллизованного зерна'],
    ['physics', 'D_a = \\left( \\frac{S_V}{\\sqrt{N_S} \\cdot 1/k} \\right)^{1/3}', 'размер аустенитного зерна феррит'],
    ['physics', '\\Delta F = 16\\pi/3 (\\sigma^3 / (\\Delta H \\Delta T / T_p + \\varepsilon)^2)', 'энергия активации зарождения феррита'],
    ['physics', '\\ln D_a = 0{,}78 + 0{,}56 \\ln D_a - 0{,}18 \\ln(V_{охл})', 'рост зерна ванадий'],
    ['physics', '\\Delta \\sigma = K f^{1/2} / D', 'упрочнение Орована-Эшби'],
    ['physics', 'd_\\gamma^n = d_{\\gamma,0}^n + K t', 'рост зерна аустенит эмпирический'],
    ['physics', 'X = 1 - \\exp(-0{,}693 (t/t_{0{,}5})^k)', 'кинетика рекристаллизации Джонсона-Мела-Аврами'],
    ['physics', 'HV = HV_{\\phi n}(V_{\\phi n}/100) + HV_{\\delta}(V_{\\delta}/100) + HV_M(V_M/100)', 'твердость структурных составляющих'],
    ['physics', '\\sigma_T (\\sigma_B) = a + b \\cdot HV', 'предел текучести твердость'],
    ['physics', '\\sigma_B = 341 + 626C + 48{,}8Si + 104{,}6Mn + 151{,}6Cr + 628{,}5Mo + 264V + 516Nb - 4{,}67H', 'прочность легирование'],
    ['physics', 'T_{рек} = 789 + 7174Nb - 50043Nb^2', 'температура рекристаллизации'],
    ['physics', '[\\sigma] = \\sigma_T / S ; [\\tau] = \\tau_T / S', 'допускаемое напряжение пластичность прочность'],
    ['physics', '[\\sigma] = \\sigma_B / S ; [\\tau] = \\tau_B / S', 'допускаемое напряжение хрупкость'],
    ['physics', '[\\sigma] = \\frac{\\sigma_{-1} \\varepsilon_\\sigma \\beta}{K_\\sigma S} ; [\\tau] = \\frac{\\tau_{-1} \\varepsilon_\\tau \\beta}{K_\\tau S}', 'переменная нагрузка пластичные материалы'],
    ['physics', '[\\sigma] = \\frac{\\sigma_B \\varepsilon_\\sigma}{K_\\sigma S} ; [\\tau] = \\frac{\\tau_B \\varepsilon_\\tau}{K_\\tau S}', 'переменная нагрузка хрупкие материалы'],
    ['physics', '\\sigma_{\\text{экв}} = \\sqrt{\\sigma^2 + \\left(\\frac{\\sigma_\\tau}{\\tau_\\tau}\\right)^2 \\tau^2} \\approx \\sqrt{\\sigma^2 + 4\\tau^2}', 'эквивалентное напряжение'],
    ['physics', 'S = \\frac{S_\\sigma S_\\tau}{\\sqrt{S_\\sigma^2 + S_\\tau^2}} \\geq [S] \\approx 1{,}5\\dots4', 'коэффициент запаса прочности'],
    ['physics', 'S_\\sigma = \\frac{\\sigma_{\\lim}}{\\frac{K_\\sigma}{\\beta \\varepsilon_\\sigma} \\sigma_a + \\psi_\\sigma \\sigma_m}', 'запас по нормальным напряжениям'],
    ['physics', 'S_\\tau = \\frac{\\tau_{\\lim}}{\\frac{K_\\tau}{\\beta \\varepsilon_\\tau} \\tau_a + \\psi_\\tau \\tau_m}', 'запас по касательным напряжениям'],
    ['physics', 'p^n S = \\text{const}', 'износ контактное давление'],
    ['physics', 'Ra = \\frac{1}{l} \\int_0^l |y| \\, dx \\quad \\text{или} \\quad Ra = \\frac{1}{n} \\sum_{i=1}^n |y_i|', 'шероховатость поверхности'],
    ['physics', 'Rz = \\frac{1}{5} \\left( \\sum_{i=1}^5 |y_{pi}| + \\sum_{i=1}^5 |y_{mi}| \\right)', 'высота неровностей'],
    ['physics', '\\sigma = F/A = F/(\\delta b) \\leq [\\sigma]', 'расчет сварного соединения на растяжение'],
    ['physics', '\\tau = F / (2l \\cdot 0{,}7k) \\leq [\\tau]', 'расчет флангового шва'],
    ['physics', 'F_1 = \\sigma_p A f + \\tau_{cp} A i', 'сила на заклепку'],
    ['physics', '\\tau_{cp} = F_1 / (A i) \\leq [\\tau_{cp}]', 'условное напряжение среза заклепки'],
    ['physics', '\\sigma_{cm} = F_1 / (S d) \\leq [\\sigma_{cm}]', 'напряжение смятия заклепки'],
    ['physics', 'F_{F_j} = F_j / z', 'нагрузка на крепежную деталь'],
    ['physics', 'F_{F_x} = F_x / z ; F_{F_y} = F_y / z ; F_{F_z} = F_z / z ; F_F = \\sqrt{F_x^2 + F_y^2}', 'равнодействующая сила'],
    ['physics', '\\sigma_{cm} = F_d / (d_c \\cdot h_{\\min}) \\leq [\\sigma_{cm}]', 'напряжение смятия'],
    ['physics', 'F_{M\\max} = \\frac{10^3 M l_{\\max}}{2 m \\sum_{i=2}^n l_i^2}', 'сила от изгибающего момента'],
    ['physics', 'W_{ctx} = J_{ctx} / y_{\\max} ; W_{cty} = J_{cty} / x_{\\max}', 'момент сопротивления сечения стыка'],
    ['physics', 'v = \\omega D / 2 = \\pi n D / 60', 'линейная скорость вращения'],
    ['physics', 'a_w = k(U \\pm 1) \\sqrt[3]{\\frac{K_H T}{\\psi_{ba} U^2 [\\sigma]_H^2}}', 'межосевое расстояние зубчатой передачи'],
    ['physics', '\\sigma_H = \\sqrt{\\frac{1}{\\pi[(1-\\nu_1^2)/E_1 + (1-\\nu_2^2)/E_2]} \\cdot \\frac{F}{l_s \\rho}} \\leq [\\sigma]_H', 'контактное напряжение Герца'],
    ['physics', '\\sigma_{\\text{экв}} = \\sqrt{(\\sigma_u + \\sigma_{p(c)})^2 + 3\\tau_k^2} \\leq [\\sigma]_u', 'эквивалентное напряжение червяка'],
    ['physics', '[\\sigma]_H = [\\sigma]_{H0} \\sqrt[9]{2 \\cdot 10^8 / N_{HE}}', 'допускаемое контактное напряжение при высокой твердости'],
    ['physics', '[\\sigma]_H = [\\sigma]_{H0} \\sqrt[6]{25 \\cdot 10^6 / N_{HE}}', 'допускаемое контактное напряжение при низкой твердости'],
    ['physics', 'S^2 = S_\\sigma^2 + S_\\tau^2 ; S = S_\\sigma \\cdot S_\\tau / \\sqrt{S_\\sigma^2 + S_\\tau^2}', 'общий коэффициент запаса прочности'],
    ['physics', '\\sum X_i = 0 \\quad \\sum Y_i = 0 \\quad \\sum Z_i = 0', 'уравнения равновесия'],
    ['physics', '\\sum M_{xi} = 0 \\quad \\sum M_{yi} = 0 \\quad \\sum M_{zi} = 0', 'уравнения равновесия моментов'],
    ['physics', 'N_z = \\sum_{k=0}^n F_{kz} \\quad Q_x = \\sum_{k=0}^n F_{kx} \\quad Q_y = \\sum_{k=0}^n F_{ky}', 'внутренние силовые факторы'],
    ['physics', 'M_z = \\sum_{k=0}^n M_z(F_k) \\quad M_x = \\sum_{k=0}^n M_x(F_k) \\quad M_y = \\sum_{k=0}^n M_y(F_k)', 'внутренние моменты'],
    ['physics', 'p = \\lim_{\\Delta A \\to 0} \\frac{\\Delta R}{\\Delta A}', 'интенсивность напряжения'],
    ['physics', 'p = \\sqrt{\\sigma_n^2 + \\tau_n^2}', 'полное напряжение'],
    ['physics', 'N = \\int_A \\sigma_z \\, dA \\quad Q_x = \\int_A \\tau_{zx} \\, dA \\quad Q_y = \\int_A \\tau_{zy} \\, dA', 'внутренние силы через интегралы'],
    ['physics', '\\sigma = \\frac{N_z}{A}', 'нормальное напряжение при растяжении-сжатии'],
    ['physics', '\\varepsilon = \\frac{\\Delta l}{l} \\quad \\varepsilon_x = \\frac{\\Delta b}{b} \\quad \\varepsilon_y = \\frac{\\Delta h}{h}', 'относительные деформации'],
    ['physics', '\\varepsilon_x = \\varepsilon_y = \\varepsilon^\\prime \\quad \\varepsilon^\\prime = \\mu \\varepsilon', 'коэффициент Пуассона'],
    ['physics', 'F = k \\Delta \\quad k = \\frac{EA}{l}', 'жесткость при растяжении-сжатии'],
    ['physics', '\\sigma = E \\varepsilon', 'закон Гука'],
    ['physics', '\\sigma = \\frac{F}{A} = E \\frac{\\Delta l}{l} \\quad \\Delta l = \\frac{F l}{EA}', 'закон Гука в относительной форме'],
    ['physics', '[\\sigma] = \\frac{\\sigma_{пред}}{[s]}', 'допускаемое напряжение'],
    ['physics', '\\sigma_{\\max} = \\frac{N}{A} \\leq [\\sigma]', 'проверочный расчет на прочность'],
    ['physics', 'A \\geq \\frac{N_{\\max}}{[\\sigma]}', 'проектный расчет сечения'],
    ['physics', '[N] = A [\\sigma]', 'допускаемая нагрузка'],
    ['physics', '\\Delta l = \\int_0^l \\frac{N(z)}{EA(z)} \\, dz \\leq [l]', 'расчет на жесткость'],
    ['physics', '\\tau_c = \\frac{Q_y}{A_c} \\quad Q = \\frac{F}{z}', 'касательное напряжение при сдвиге'],
    ['physics', '\\tau = G \\gamma \\quad G = \\frac{E}{2(1+\\mu)}', 'закон Гука при сдвиге'],
    ['physics', 'M_z = \\int_A \\tau \\rho \\, dA', 'крутящий момент'],
    ['physics', '\\varphi = \\frac{M_k l}{G J_p}', 'угол закручивания'],
    ['physics', '\\theta = \\frac{d\\varphi}{dz} = \\frac{\\varphi}{l} = \\frac{M_k}{G J_p}', 'относительный угол закручивания'],
    ['physics', '\\tau_{\\max} = \\frac{M_k \\rho_{\\max}}{J_p} \\quad W_p = \\frac{J_p}{\\rho_{\\max}}', 'максимальное касательное напряжение при кручении'],
    ['physics', '\\tau_{\\max} = \\frac{M_k}{W_p}', 'условие прочности при кручении'],
    ['physics', 'W_p = \\alpha h b^2', 'момент сопротивления при кручении прямоугольника'],
    ['physics', 'J_p = \\beta h b^3', 'полярный момент инерции прямоугольника'],
    ['physics', 'W_p = \\frac{\\pi D^3}{16}', 'момент сопротивления круглого сечения'],
    ['physics', 'D \\geq \\sqrt[3]{\\frac{16 M_k}{\\pi [\\tau]}}', 'проектный расчет диаметра вала'],
    ['physics', '\\frac{dQ_y}{dz} = q \\quad \\frac{dM_x}{dz} = Q_y', 'дифференциальные зависимости Журавского'],
    ['physics', '\\sigma_z = \\frac{M_x y}{J_x} \\quad \\sigma_{\\max} = \\frac{M_x}{W_x}', 'нормальное напряжение при изгибе'],
    ['physics', '\\tau = \\frac{Q_y S_x^{omc}}{J_x b}', 'касательное напряжение при изгибе (формула Журавского)'],
    ['physics', 'J_x = \\int_A y^2 \\, dA \\quad J_y = \\int_A x^2 \\, dA', 'осевые моменты инерции'],
    ['physics', 'J_p = \\int_A (x^2 + y^2) \\, dA = \\int_A \\rho^2 \\, dA', 'полярный момент инерции'],
    ['physics', 'S_x = \\sum_{k=1}^n A_k y_k \\quad S_y = \\sum_{k=1}^n A_k x_k', 'статические моменты площади'],
    ['physics', 'x_c = \\frac{\\sum A_k x_k}{\\sum A_k} \\quad y_c = \\frac{\\sum A_k y_k}{\\sum A_k}', 'координаты центра тяжести'],
    ['physics', '\\sigma_{\\text{экв}} = \\frac{\\sigma_x + \\sigma_y}{2} + \\frac{1}{2} \\sqrt{(\\sigma_x - \\sigma_y)^2 + 4\\tau_{xy}^2}', 'эквивалентное напряжение (Губера-Мизеса)'],
    ['physics', '\\sigma_{\\text{экв}} = \\sigma_1 - \\mu(\\sigma_2 + \\sigma_3) \\leq [\\sigma]', 'эквивалентное напряжение по относительным удлинениям'],
    ['physics', 'F_{кр} = \\frac{\\pi^2 E J_{\\min}}{l^2}', 'формула Эйлера (критическая сила)'],
    ['physics', 'F_{кр} = \\frac{\\pi^2 E J_{\\min}}{(\\mu l)^2}', 'формула Эйлера с коэффициентом приведения длины'],
    ['physics', '\\sigma_{кр} = \\frac{\\pi^2 E}{\\lambda^2}', 'критическое напряжение'],
    ['physics', '\\lambda = \\frac{\\mu l}{i_{\\min}}', 'гибкость стержня'],
    ['physics', '\\sigma_T = \\sigma_i + K_Y \\cdot d^{-1/2}', 'уравнение Холла-Петча'],
    ['physics', '\\sigma_T = \\sigma_0 + \\Delta\\sigma_{\\text{ТР}} + \\Delta\\sigma_{\\text{ДУ}} + \\Delta\\sigma_{\\text{Д}} + \\Delta\\sigma_{\\text{П}} + \\Delta\\sigma_3', 'упрочнение феррито-перлитной стали'],
    ['physics', '\\sigma_0 = 2G \\cdot 10^{-4}', 'напряжение трения решётки'],
    ['physics', '\\Delta\\sigma_{\\text{ТР}} = \\sum_{i=1}^n K_i C_i', 'твердорастворное упрочнение'],
    ['physics', '\\Delta\\sigma_{\\text{Д}} = \\alpha m G b \\rho^{1/2}', 'деформационное упрочнение'],
    ['physics', 'E = \\alpha G b^2', 'энергия дислокации (упрощённая)'],
    ['physics', '\\vec{\\omega} = \\frac{d^2 V}{dS dt} \\vec{n}', 'скорость жидкости в точке'],
    ['physics', '\\vec{\\omega} = \\frac{d \\dot{V}}{dS} \\vec{n}', 'скорость через поверхность'],
    ['physics', '\\frac{\\partial \\rho}{\\partial t} + \\div(\\rho \\vec{\\omega}) = 0', 'уравнение неразрывности'],
    ['physics', '\\frac{dM}{dx} = 0 \\quad \\text{или} \\quad \\dot{M} = \\text{const}', 'интегральная форма неразрывности'],
    ['physics', '\\frac{d \\vec{\\omega}}{dt} = \\vec{f}^{en} - \\frac{1}{\\rho} \\nabla p', 'уравнение Эйлера'],
    ['physics', '\\frac{d\\vec{\\omega}}{dt} = \\vec{f}^{en} - \\frac{1}{\\rho} \\nabla p + \\nu \\nabla^2 \\vec{\\omega}', 'уравнение Навье-Стокса (несжимаемая жидкость)'],
    ['physics', '\\frac{\\rho u^2}{2} + p + \\rho g z = \\text{const}', 'уравнение Бернулли (идеальная жидкость)'],
    ['physics', '\\alpha_1 \\frac{\\rho_1 \\bar{u}_1^2}{2} + \\bar{p}_1 + \\rho_1 g z_1 = \\alpha_2 \\frac{\\rho_2 \\bar{u}_2^2}{2} + \\bar{p}_2 + \\rho_2 g z_2 + \\Delta p_{1-2}', 'уравнение Бернулли (реальная жидкость)'],
    ['physics', '\\Delta p^{\\text{пот}} = \\xi \\frac{\\rho \\bar{u}^2}{2}', 'потери давления (коэффициент гидравлического сопротивления)'],
    ['physics', '\\Delta p^{\\text{тр}} = \\lambda \\frac{L}{d} \\frac{\\rho \\bar{u}^2}{2}', 'потери на трение в трубе'],
    ['physics', '\\lambda = \\frac{64}{\\text{Re}}', 'коэффициент трения (ламинарный режим)'],
    ['physics', '\\lambda = 0{,}316 \\text{Re}^{-0{,}25}', 'формула Блазиуса (гладкая труба, турбулентный)'],
    ['physics', '\\lambda = [2 \\lg(d / 2\\Delta) + 1{,}74]^{-2}', 'формула Никурадзе (шероховатая труба)'],
    ['physics', 'p v = \\text{const}', 'закон Бойля-Мариотта'],
    ['physics', 'v_1 / v_2 = T_1 / T_2', 'закон Гей-Люссака'],
    ['physics', 'p_1 / p_2 = T_1 / T_2', 'закон Шарля'],
    ['physics', 'p v = \\mu R T', 'уравнение состояния идеального газа (молярное)'],
    ['physics', 'p V = m R_s T', 'уравнение состояния (удельное)'],
    ['physics', 'q = -\\lambda \\frac{dT}{dx}', 'закон Фурье (теплопроводность)'],
    ['physics', 'Q = \\alpha A (T_w - T_f)', 'закон Ньютона-Рихмана (конвективный теплообмен)'],
    ['physics', 'Q = \\varepsilon \\sigma A (T_1^4 - T_2^4)', 'закон Стефана-Больцмана (излучение)'],
    ['physics', 'Nu = f(\\text{Re}, \\text{Pr})', 'критерий Нуссельта (теплоотдача)'],
    ['physics', '\\text{Pr} = \\frac{\\nu}{a}', 'число Прандтля'],
    ['physics', '\\text{Re} = \\frac{u d}{\\nu}', 'число Рейнольдса'],
    ['physics', '\\text{Gr} = \\frac{g \\beta \\Delta T L^3}{\\nu^2}', 'число Грасгофа (свободная конвекция)'],
    ['physics', 'Bi = \\frac{\\alpha L}{\\lambda}', 'число Био (критерий теплообмена)'],
    ['physics', 'Fo = \\frac{a \\tau}{L^2}', 'число Фурье (нестационарная теплопроводность)'],
    ['physics', 'q = \\alpha (T_w - T_\\infty) + \\varepsilon \\sigma (T_w^4 - T_\\text{окр}^4)', 'суммарный теплообмен (конвекция + излучение)'],
    ['physics', 'T_r = \\frac{Q_T + Q_d + J}{V_c}', 'теоретическая температура горения'],
    ['physics', '\\Delta G = \\Delta H - T \\Delta S', 'энергия Гиббса (для металлургических реакций)'],
    ['physics', 'h_0 \\cdot b_0 \\cdot l_0 = h_1 \\cdot b_1 \\cdot l_1', 'условие постоянства объёма при прокатке'],
    ['physics', '\\frac{h_1 \\cdot b_1 \\cdot l_1}{h_0 \\cdot b_0 \\cdot l_0} = 1', 'относительная форма условия постоянства объёма'],
    ['physics', '\\frac{\\beta \\cdot \\lambda}{\\eta} = 1', 'коэффициенты деформации'],
    ['physics', '-\\ln(\\eta) + \\ln(\\beta) + \\ln(\\lambda) = 0', 'логарифмическая форма постоянства объёма'],
    ['physics', '\\eta = \\frac{h_0}{h_1}', 'коэффициент высотной деформации'],
    ['physics', '\\beta = \\frac{b_1}{b_0}', 'коэффициент поперечной деформации'],
    ['physics', '\\lambda = \\frac{l_1}{l_0}', 'коэффициент продольной деформации'],
    ['physics', '\\varepsilon = \\frac{h_0 - h_1}{h_0} \\cdot 100\\%', 'относительное обжатие'],
    ['physics', '\\mu = \\frac{F_0}{F_1} = \\frac{h_0 \\cdot b_0}{h_1 \\cdot b_1}', 'коэффициент вытяжки'],
    ['physics', '\\mu_{ср} = \\sqrt[n]{\\mu_\\Sigma}', 'средний коэффициент вытяжки'],
    ['physics', '\\delta = h_1 - s_0', 'пружина клети'],
    ['physics', 'M_k = \\operatorname{tg} \\theta = \\frac{\\Delta P}{\\Delta \\delta}', 'модуль жёсткости клети'],
    ['physics', 'h_1 = s_0 + \\delta', 'толщина полосы с учётом пружины'],
    ['physics', '\\delta = s_1 + \\frac{P}{\\operatorname{tg}\\theta} = s_1 + \\frac{P}{M_k}', 'пружина с учётом начального зазора'],
    ['physics', 'h_1 = s_0 + s_1 + \\frac{P}{M_k}', 'расчётная толщина полосы'],
    ['physics', 'f_k = \\sum_{i=1}^n f_i', 'общая упругая деформация клети'],
    ['physics', 'f_b = f_1 + f_2', 'стрела прогиба валка'],
    ['physics', 'f_b = 2(f_1 + f_2)', 'стрела прогиба двух валков'],
    ['physics', 'f_c = f_1 + f_2 + f_3', 'деформация станины'],
    ['physics', 'f_1 = \\frac{P}{18{,}8 E D^4} \\left\\{ 8a^3 - 4ab^2 + e^3 + 64c^2 \\left[ \\left( \\frac{D}{d} \\right)^4 - 1 \\right] \\right\\}', 'стрела прогиба от изгибающего момента'],
    ['physics', 'f_2 = \\frac{P}{G \\pi D^2} \\left( a - \\frac{e}{2} + 2c \\left[ \\left( \\frac{D}{d} \\right)^2 - 1 \\right] \\right)', 'стрела прогиба от поперечных сил'],
    ['physics', 'f_1 = \\frac{p_1 l_1^3}{24 E I_1} - \\frac{M_0 l_1^2}{4 E I_1}', 'деформация поперечины от изгиба'],
    ['physics', 'f_2 = \\frac{p_1 l_2}{2 E F_2}', 'деформация стоек от продольных сил'],
    ['physics', 'f_3 = \\frac{1{,}2 p_1 l_1}{2 G F_1}', 'деформация поперечины от поперечных сил'],
    ['physics', 'X = \\bar{x} \\pm \\Delta x', 'результат измерения среднее значение погрешность'],
    ['physics', '\\Delta x = t_{\\alpha, n} \\cdot \\frac{s}{\\sqrt{n}}', 'доверительная погрешность коэффициент стьюдента среднеквадратичное отклонение'],
    ['physics', 'x = \\frac{1}{n} \\sum_{i=1}^n x_i', 'среднее арифметическое результат измерения'],
    ['physics', 's = \\sqrt{\\frac{1}{n-1} \\sum_{i=1}^n (x_i - \\bar{x})^2}', 'среднеквадратичное отклонение выборки'],
    ['physics', '\\sigma = \\lim_{n \\to \\infty} \\sqrt{\\frac{1}{n} \\sum_{i=1}^n (x_i - \\mu)^2}', 'среднеквадратичное отклонение генеральной совокупности'],
    ['physics', '\\delta = \\frac{\\Delta x}{x} \\cdot 100\\%', 'относительная погрешность измерения'],
    ['physics', '\\Delta_{\\text{сист}} = \\sum_{i=1}^k \\Delta_i', 'систематическая погрешность сумма составляющих'],
    ['physics', '\\Delta_{\\text{случ}} = k \\cdot \\sigma', 'случайная погрешность коэффициент квантиль'],
    ['physics', 'R = x_{\\max} - x_{\\min}', 'размах выборки'],
    ['physics', 'CV = \\frac{\\sigma}{\\mu} \\cdot 100\\%', 'коэффициент вариации'],
    ['physics', 'ES = D_{\\max} - D', 'верхнее предельное отклонение отверстия'],
    ['physics', 'EI = D_{\\min} - D', 'нижнее предельное отклонение отверстия'],
    ['physics', 'es = d_{\\max} - d', 'верхнее предельное отклонение вала'],
    ['physics', 'ei = d_{\\min} - d', 'нижнее предельное отклонение вала'],
    ['physics', 'TD = ES - EI', 'допуск отверстия'],
    ['physics', 'Td = es - ei', 'допуск вала'],
    ['physics', 'IT_n = 10^{0.2 \\cdot (n-1)} \\cdot 2.5', 'квалитет допуска по единице допуска'],
    ['physics', 'i = 0.45 \\sqrt[3]{D} + 0.001D', 'единица допуска интервал размеров'],
    ['physics', 'a = \\frac{TD}{i}', 'число единиц допуска квалитет'],
    ['physics', 'S = D_{\\min} - d_{\\max}', 'наименьший зазор'],
    ['physics', 'N = d_{\\min} - D_{\\max}', 'наибольший натяг'],
    ['physics', 'S_m = \\frac{S_{\\min} + S_{\\max}}{2}', 'средний зазор'],
    ['physics', 'T_N = N_{\\max} - N_{\\min} = TD + Td', 'допуск посадки с натягом'],
    ['physics', 'T_S = S_{\\max} - S_{\\min} = TD + Td', 'допуск посадки с зазором'],
    ['physics', 'T_{SN} = S_{\\max} + N_{\\max} = TD + Td', 'допуск переходной посадки'],
    ['physics', 'Ra = \\frac{1}{l} \\int_0^l |y(x)| dx', 'среднеарифметическое отклонение профиля шероховатость'],
    ['physics', 'Rz = \\frac{1}{5} \\left( \\sum_{i=1}^5 y_{pi} + \\sum_{i=1}^5 y_{mi} \\right)', 'высота неровностей профиля по десяти точкам'],
    ['physics', 'R_{\\max} = \\max(|y_{p\\max}|, |y_{m\\max}|)', 'максимальная высота неровностей профиля'],
    ['physics', 'S_m = \\frac{1}{n} \\sum_{i=1}^n S_i', 'средний шаг неровностей профиля'],
    ['physics', 't_p = \\frac{\\eta_p}{l} \\cdot 100\\%', 'относительная опорная длина профиля уровень сечения'],
    ['physics', 'R_a = R_z / 4 \\quad \\text{(приближённо)}', 'связь параметров шероховатости'],
    ['physics', 'C = \\frac{S_t - S_b}{t_t - t_b}', 'коэффициент калибровки чувствительность прибора'],
    ['physics', 'L = \\alpha L_0 \\Delta T', 'температурное расширение стандартного образца'],
    ['physics', '\\Delta = A_{\\text{поверяемый}} - A_{\\text{эталон}}', 'показание поверяемого прибора поправка'],
    ['physics', 'd^* = \\frac{d}{\\sqrt{t}}', 'приведённая нестабильность измерений'],
    ['physics', 'MSA = \\frac{\\sigma_{\\text{изм}}^2}{\\sigma_{\\text{общ}}^2} \\cdot 100\\%', 'анализ измерительной системы повторяемость воспроизводимость'],
    ['physics', 'GRR = \\sqrt{\\text{EV}^2 + \\text{AV}^2} \\cdot 100\\%', 'повторяемость и воспроизводимость измерительной системы'],
    ['physics', 'v_{\\text{зал}} = \\frac{Q}{S_{\\text{литн}}}', 'скорость заливки металла в форму расход площадь литниковой системы'],
    ['physics', 't_{\\text{зал}} = \\frac{m}{\\rho \\cdot Q}', 'время заливки масса плотность расход'],
    ['physics', 'H_p = H_0 - \\frac{h_c^2}{2g \\mu^2}', 'действующий напор в литниковой системе гидравлика'],
    ['physics', 'Q = \\mu \\cdot F \\cdot \\sqrt{2gH_p}', 'расход металла через литниковую систему коэффициент расхода'],
    ['physics', '\\mu = \\frac{1}{\\sqrt{1 + \\xi + \\lambda \\frac{l}{d}}}', 'коэффициент расхода литниковой системы'],
    ['physics', '\\xi_{\\text{пов}} = \\left( \\frac{F_{\\text{вх}}}{F_{\\text{вых}}} - 1 \\right)^2', 'коэффициент местного сопротивления при расширении'],
    ['physics', '\\sum F_{\\text{ст}} : \\sum F_{\\text{шл}} : \\sum F_{\\text{пит}} = 1 : 1.1 : 1.2', 'соотношение сечений литниковой системы стояк шлакоуловитель питатель'],
    ['physics', 'R = \\frac{2\\gamma}{r \\cdot \\rho \\cdot g}', 'радиус скругления углов отливки капиллярные силы'],
    ['physics', '\\tau = \\frac{4M^2}{\\pi^2 a} \\left( \\frac{T_{\\text{зал}} - T_{\\text{ф}}}{T_{\\text{лик}} - T_{\\text{ф}}} \\right)', 'время затвердевания отливки массивность коэффициент теплопроводности'],
    ['physics', 'V_{\\text{кр}} = \\frac{C \\cdot S_{\\text{охл}}}{\\sqrt{\\tau}} \\cdot \\exp\\left(-\\frac{Q}{RT}\\right)', 'скорость кристаллизации площадь охлаждения'],
    ['physics', 's = K \\cdot \\sqrt{\\tau}', 'толщина затвердевшего слоя коэффициент затвердевания'],
    ['physics', 'K = \\frac{2}{\\sqrt{\\pi}} \\cdot \\frac{T_{\\text{зал}} - T_{\\text{лик}}}{\\rho L} \\sqrt{\\lambda c \\rho}', 'коэффициент затвердевания скрытая теплота'],
    ['physics', 'Bi = \\frac{\\alpha \\cdot R}{\\lambda}', 'критерий биотемпературное поле отливки'],
    ['physics', 'Fo = \\frac{a \\cdot \\tau}{R^2}', 'критерий фурье время затвердевания'],
    ['physics', '\\frac{\\partial T}{\\partial t} = a \\nabla^2 T + \\frac{L}{c} \\frac{\\partial f_s}{\\partial t}', 'уравнение теплопроводности с выделением скрытой теплоты кристаллизации'],
    ['physics', 'f_s = 1 - \\exp\\left(-k \\cdot \\frac{T_{\\text{лик}} - T}{T_{\\text{лик}} - T_{\\text{сол}}}\\right)', 'доля твёрдой фазы температура'],
    ['physics', 'P = \\frac{\\Delta P_{\\text{кр}}}{\\rho g h}', 'вероятность образования усадочной раковины'],
    ['physics', 'V_{\\text{усад}} = \\beta \\cdot V_0 \\cdot \\Delta T', 'объёмная усадка коэффициент усадки'],
    ['physics', '\\varepsilon_{\\text{лин}} = \\alpha_{\\text{л}} \\cdot \\Delta T', 'линейная усадка коэффициент линейного расширения'],
    ['physics', 'D_{\\text{пор}} = \\sqrt{\\frac{6 \\cdot V_{\\text{газ}}}{\\pi \\cdot N}}', 'диаметр газовой пористости объём газа число пор'],
    ['physics', 'P_{\\text{коп}} = \\frac{1}{2} \\rho v^2 C_D', 'давление копота в форме гидравлическое сопротивление'],
    ['physics', 'R_a = \\frac{\\sigma}{2} \\left( \\frac{1}{r_1} + \\frac{1}{r_2} \\right)', 'давление лапласа радиус кривизны мениска'],
    ['physics', 'Re = \\frac{v \\cdot d}{\\nu}', 'число рейнольдса для течения расплава в форме'],
    ['physics', 'We = \\frac{\\rho v^2 d}{\\sigma}', 'число вебера разбрызгивание расплава'],
    ['physics', 'Fr = \\frac{v^2}{g d}', 'число фруда турбулентность расплава'],
    ['physics', 'v_{\\text{ц}} = \\frac{g}{n^2 R}', 'скорость вращения при центробежном литье'],
    ['physics', 'P_{\\text{ц}} = \\frac{\\rho \\omega^2 R^2}{2}', 'давление в форме при центробежном литье'],
    ['physics', 'G = \\frac{m \\omega^2 R}{g}', 'сила тяжести при центробежном литье'],
    ['physics', '\\xi = 1 - \\frac{F_{\\text{пор}}}{F_{\\text{общ}}}', 'коэффициент плотности отливки'],
    ['physics', '\\eta = \\frac{m_{\\text{годн}}}{m_{\\text{залит}}} \\cdot 100\\%', 'выход годного литья технологический'],
    ['physics', 'R = \\frac{0.61 \\lambda}{NA}', 'разрешающая способность оптического микроскопа длина волны числовая апертура'],
    ['physics', 'NA = n \\sin \\alpha', 'числовая апертура показатель преломления угловая апертура'],
    ['physics', 'G = \\frac{L}{f_1} \\cdot \\frac{250}{f_2}', 'общее увеличение микроскопа окуляр объектив'],
    ['physics', 'DOF = \\frac{\\lambda}{2 n \\sin^2 \\alpha}', 'глубина резкости микроскоп апертура'],
    ['physics', 'Z = \\frac{n \\cdot \\lambda}{2 \\cdot NA^2}', 'глубина фокуса микроскопа'],
    ['physics', 'D_{el} = D_{1.5-2} \\cdot M \\cdot 10^{-3}', 'диаметр поля зрения микроскопа'],
    ['physics', '\\lambda_e = \\frac{h}{\\sqrt{2 m_e e U}}', 'длина волны электрона ускоряющее напряжение просвечивающая микроскопия'],
    ['physics', 'd = \\frac{0.61 \\lambda}{\\beta}', 'пятно электронного зонда растровая микроскопия'],
    ['physics', 'I_{SE} = I_0 \\cdot \\delta \\cdot \\exp\\left(-\\frac{z}{\\lambda_{SE}}\\right)', 'интенсивность вторичных электронов растр'],
    ['physics', '\\theta_B = \\arctan\\left(\\frac{x}{f}\\right)', 'угол брюстера микроскопия'],
    ['physics', 'E_{BSE} = E_0 \\cdot \\eta', 'энергия обратно рассеянных электронов растр'],
    ['physics', 'r_{BSE} = 0.006 \\cdot (E_0)^{1.5} / \\rho', 'диаметр области генерации обратно рассеянных электронов'],
    ['physics', 'Z_{AB} = \\frac{2}{1/Z_A + 1/Z_B}', 'усреднённый атомный номер контраст изображения'],
    ['physics', 'F_{hkl} = \\sum_{j=1}^N f_j \\exp(2\\pi i (hx_j + ky_j + lz_j))', 'структурный фактор электронная дифракция'],
    ['physics', 'I_{hkl} = K \\cdot |F_{hkl}|^2 \\cdot p \\cdot L(\\theta) \\cdot A(\\theta) \\cdot \\exp(-2B \\sin^2 \\theta / \\lambda^2)', 'интенсивность дифракционного отражения'],
    ['physics', 'd_{hkl} = \\frac{\\lambda}{2 \\sin \\theta_{hkl}}', 'межплоскостное расстояние дифракция кристалл'],
    ['physics', '\\Delta \\theta = \\frac{\\lambda}{2 \\Delta r}', 'ширина дифракционного рефлекса размер когерентной области'],
    ['physics', 'D = \\frac{K \\lambda}{\\beta \\cos \\theta}', 'размер кристаллита шерер уравнение ширина пика'],
    ['physics', '\\varepsilon = \\frac{\\beta}{4 \\tan \\theta}', 'деформация решётки из уширения дифракционного пика'],
    ['physics', 'G = \\frac{\\ln \\frac{D_{\\text{ср}}}{10}}{\\ln 2} + 1', 'номер зерна по астм средний диаметр'],
    ['physics', 'N = 2^{n-1}', 'среднее число зёрен на единицу площади'],
    ['physics', 'A = \\frac{n}{S}', 'удельная площадь поверхности границ зёрен'],
    ['physics', 'D = \\frac{4S}{\\pi N}', 'средний диаметр зерна из числа пересечений'],
    ['physics', 'L = \\frac{N}{M \\cdot P}', 'средняя длина хорды металлография'],
    ['physics', 'V_v = A_A = L_L = P_P', 'принцип делиссе объёмная доля фазы площадь доля линейная доля точечная доля'],
    ['physics', 'S_v = \\frac{2P_L}{\\pi}', 'удельная поверхность раздела фаз металлография'],
    ['physics', 'P_L = \\frac{P}{L}', 'количество пересечений на единицу длины'],
    ['physics', 'n_A = \\frac{N_A}{A_f}', 'число частиц на единицу площади шлиф'],
    ['physics', 'V_{v} = \\frac{\\sum A_{\\phi}}{A_{\\text{общ}}}', 'объёмная доля фазы по площади на микрошлифе'],
    ['physics', 'f_i = \\frac{I_i / R_i}{\\sum_{j=1}^n I_j / R_j}', 'количественный рентгенофазовый анализ'],
    ['physics', 'R_i = \\frac{K_i}{\\mu_m}', 'фактор рентгенофазового анализа'],
    ['physics', '\\frac{I_i}{I_{макс}} = \\frac{1}{1 + \\exp(-k(x - x_p))}', 'сигмоидная калибровка количественного анализа'],
    ['physics', 'C_i = \\frac{Z_i A_i F_i}{W_i} \\cdot \\frac{I_i}{I_i^{\\text{стандарт}}}', 'поправка на атомный номер поглощение флуоресценцию микроанализ'],
    ['physics', '\\mu = \\sum w_i \\mu_i', 'линейный коэффициент ослабления рентгена аддитивность'],
    ['physics', 'S_v = \\frac{2}{\\pi} \\cdot \\frac{N_L}{M}', 'удельная поверхность стереология металлография'],
    ['physics', 'L_v = \\frac{2 \\pi^2}{3} \\cdot \\frac{N_L^2}{M^2 N_A}', 'общая длина границ фаз в объёме'],
    ['physics', '\\bar{L}_3 = \\frac{2}{N_L \\cdot M}', 'средний размер частиц в пространстве'],
    ['physics', '\\lambda = \\frac{1}{N_L \\cdot M}', 'среднее расстояние между частицами'],
    ['physics', 'R = \\frac{3}{4} \\cdot \\frac{V_v}{S_v}', 'средний радиус частиц при сферической форме'],
    ['physics', '\\sigma = \\frac{F}{S_0}', 'напряжение растяжения сила начальная площадь сечения'],
    ['physics', '\\varepsilon = \\frac{l - l_0}{l_0} \\cdot 100\\%', 'относительное удлинение деформация'],
    ['physics', '\\sigma_B = \\frac{F_{\\max}}{S_0}', 'предел прочности временное сопротивление растяжению'],
    ['physics', '\\sigma_T = \\frac{F_T}{S_0}', 'предел текучести физический'],
    ['physics', '\\sigma_{0.2} = \\frac{F_{0.2}}{S_0}', 'условный предел текучести остаточная деформация 0.2%'],
    ['physics', '\\psi = \\frac{S_0 - S_{\\text{к}}}{S_0} \\cdot 100\\%', 'относительное сужение площадь поперечного сечения'],
    ['physics', 'E = \\frac{\\sigma}{\\varepsilon}', 'модуль юнга модуль упругости напряжение деформация'],
    ['physics', '\\mu = \\left| \\frac{\\varepsilon_{\\text{попер}}}{\\varepsilon_{\\text{прод}}} \\right|', 'коэффициент пуассона поперечная деформация'],
    ['physics', 'K = \\frac{E}{3(1-2\\mu)}', 'модуль объёмного сжатия'],
    ['physics', 'G = \\frac{E}{2(1+\\mu)}', 'модуль сдвига через модуль юнга и пуассона'],
    ['physics', 'w = \\int_0^{\\varepsilon_B} \\sigma d\\varepsilon', 'удельная работа деформации пластичность'],
    ['physics', 'n = \\frac{d\\ln\\sigma}{d\\ln\\varepsilon_p}', 'показатель деформационного упрочнения'],
    ['physics', '\\sigma = K \\varepsilon_p^n', 'закон упрочнения холломона напряжение деформация'],
    ['physics', 'HB = \\frac{2F}{\\pi D(D - \\sqrt{D^2 - d^2})}', 'твердость по бринеллю сила диаметр индентора отпечаток'],
    ['physics', 'HRC = 100 - \\frac{h}{0.002}', 'твёрдость по роквеллу шкала c глубина вдавливания'],
    ['physics', 'HV = 1.854 \\frac{F}{d^2}', 'твёрдость по виккерсу сила диагональ отпечатка'],
    ['physics', 'HV = \\frac{0.1891F}{d^2}', 'твёрдость по виккерсу альтернативная формула'],
    ['physics', 'HK = 14.23 \\frac{F}{l^2}', 'твёрдость по кнупу сила длина отпечатка'],
    ['physics', 'HS = \\frac{100}{\\text{высота отскока}}', 'твёрдость по шору упругий отскок'],
    ['physics', 'HB \\approx 3.45 \\cdot HRC', 'пересчёт твёрдости бринелль в роквелл'],
    ['physics', 'HV \\approx HB \\quad \\text{при} \\quad HV < 400', 'приближённое равенство виккерса и бринелля'],
    ['physics', '\\sigma_B \\approx 3.5 \\cdot HB', 'связь прочности с твёрдостью по бринеллю'],
    ['physics', 'KCU = \\frac{A}{S_{\\text{надр}}}', 'ударная вязкость образец с концентратором работа удара'],
    ['physics', 'KCV = \\frac{A}{S_{\\text{надр}}}', 'ударная вязкость образец с v-образным надрезом'],
    ['physics', 'KCT = \\frac{A}{S_{\\text{надр}}}', 'ударная вязкость образец с трещиной'],
    ['physics', 'T_{50} = \\frac{T_1 + T_2}{2}', 'температура 50% вязкого излома хладноломкость'],
    ['physics', 'F = mg(h_1 - h_2)', 'работа удара маятникового копра масса гравитация высота подъёма'],
    ['physics', '\\Delta KCV = KCV_{\\text{max}} - KCV_{\\text{min}}', 'диапазон изменения ударной вязкости'],
    ['physics', '\\sigma_{-1} = \\frac{\\sigma_{\\max} - \\sigma_{\\min}}{2}', 'предел выносливости при симметричном цикле'],
    ['physics', 'R = \\frac{\\sigma_{\\min}}{\\sigma_{\\max}}', 'коэффициент асимметрии цикла напряжений'],
    ['physics', '\\sigma_a = \\frac{\\sigma_{\\max} - \\sigma_{\\min}}{2}', 'амплитуда цикла напряжений'],
    ['physics', '\\sigma_m = \\frac{\\sigma_{\\max} + \\sigma_{\\min}}{2}', 'среднее напряжение цикла'],
    ['physics', '\\sigma_a = \\sigma_{-1} \\left(1 - \\frac{\\sigma_m}{\\sigma_B}\\right)', 'диаграмма гаудера предела выносливости'],
    ['physics', '\\sigma_a = \\sigma_{-1} - k \\sigma_m', 'линейная зависимость предела выносливости от среднего напряжения'],
    ['physics', 'N \\sigma^m = C', 'уравнение велера кривая усталости число циклов напряжение'],
    ['physics', '\\sigma = \\sigma_{-1} \\sqrt[3]{\\frac{10^6}{N}}', 'предел выносливости для заданного числа циклов'],
    ['physics', 'D = \\sum_{i=1}^k \\frac{n_i}{N_i} = 1', 'правило пальмгрена майнера накопление повреждений'],
    ['physics', 'K_t = \\frac{\\sigma_{\\max}}{\\sigma_{\\text{ном}}}', 'коэффициент концентрации напряжений'],
    ['physics', 'K_f = 1 + q(K_t - 1)', 'эффективный коэффициент концентрации чувствительность к надрезу'],
    ['physics', '\\dot{\\varepsilon} = A \\sigma^n \\exp\\left(-\\frac{Q}{RT}\\right)', 'скорость ползучести напряжение температура энергия активации'],
    ['physics', '\\varepsilon(t) = \\varepsilon_0 + \\dot{\\varepsilon}_1 t + \\dot{\\varepsilon}_2 t^3', 'кривая ползучести три стадии'],
    ['physics', 't_{\\text{разр}} = \\frac{C}{\\sigma^m} \\exp\\left(\\frac{U}{RT}\\right)', 'время до разрушения при ползучести'],
    ['physics', '\\sigma_{1000}^{T} = \\frac{A}{t^{1/n}}', 'длительная прочность при заданной температуре'],
    ['physics', '\\varepsilon_{\\min} = B \\sigma^n', 'минимальная скорость ползучести закон нортона'],
    ['physics', 'K_I = \\sigma \\sqrt{\\pi a} Y', 'коэффициент интенсивности напряжений трещина'],
    ['physics', 'K_{IC} = \\frac{P_Q}{B\\sqrt{W}} f\\left(\\frac{a}{W}\\right)', 'вязкость разрушения плоская деформация'],
    ['physics', 'Y = 1.12 - 0.23(a/W) + 10.6(a/W)^2 - 21.7(a/W)^3 + 30.4(a/W)^4', 'фактор формы для образца с краевой трещиной'],
    ['physics', 'B \\geq 2.5 \\left(\\frac{K_{IC}}{\\sigma_T}\\right)^2', 'критерий плоской деформации толщина образца'],
    ['physics', 'J_{IC} = \\frac{U}{B(W-a)}', 'интеграл дж равновесная трещиностойкость'],
    ['physics', 'I = \\frac{\\Delta m}{\\rho \\cdot L}', 'интенсивность изнашивания потеря массы плотность путь трения'],
    ['physics', 'k = \\frac{V}{F_{\\text{норм}} \\cdot L}', 'коэффициент износа объём нормальная сила путь'],
    ['physics', '\\tan \\beta = \\frac{\\Delta h}{\\Delta t}', 'скорость изнашивания глубина время'],
    ['physics', 'W = K \\cdot \\frac{P}{H}', 'закон архарда объёмный износ нагрузка твёрдость'],
    ['physics', 'V = \\frac{k \\cdot P \\cdot L}{H}', 'объём изношенного материала коэффициент нагрузки путь твёрдость'],
    ['physics', '\\frac{da}{dN} = C(\\Delta K)^m', 'закон париса скорость роста усталостной трещины'],
    ['physics', '\\Delta K = \\Delta \\sigma \\sqrt{\\pi a}', 'размах коэффициента интенсивности напряжений'],
    ['physics', 'a_f = \\frac{1}{\\pi} \\left(\\frac{K_{IC}}{\\sigma_{\\max}}\\right)^2', 'критический размер трещины'],
    ['physics', 'N_f = \\int_{a_0}^{a_f} \\frac{da}{C(\\Delta K)^m}', 'число циклов до разрушения трещина'],
    ['physics', '\\sigma_R = \\frac{\\sigma_{\\max} - \\sigma_{\\min}}{2\\sqrt{1-R}}', 'приведённое напряжение по морроу'],
    ['physics', 'U = Q - W', 'первое начало термодинамики внутренняя энергия теплота работа'],
    ['physics', 'dU = TdS - pdV', 'дифференциал внутренней энергии энтропия объем'],
    ['physics', 'H = U + pV', 'энтальпия внутренняя энергия произведение давления на объем'],
    ['physics', 'dH = TdS + Vdp', 'дифференциал энтальпии энтропия давление'],
    ['physics', 'F = U - TS', 'энергия гельмгольца свободная энергия'],
    ['physics', 'G = H - TS', 'энергия гиббса изобарно изотермический потенциал'],
    ['physics', 'dG = Vdp - SdT', 'дифференциал энергии гиббса'],
    ['physics', '\\Delta G_T^\\circ = \\Delta H_T^\\circ - T \\Delta S_T^\\circ', 'изменение энергии гиббса при температуре t'],
    ['physics', '\\Delta H_T = \\Delta H_{298} + \\int_{298}^T \\Delta C_p dT', 'энтальпия при температуре через теплоемкость'],
    ['physics', '\\Delta S_T = \\Delta S_{298} + \\int_{298}^T \\frac{\\Delta C_p}{T} dT', 'энтропия при температуре через теплоемкость'],
    ['physics', 'C_p - C_v = \\alpha^2 V T / \\beta', 'разность теплоемкостей при постоянном давлении и объеме'],
    ['physics', '\\Delta C_p = \\sum \\nu_i C_{p,i}(\\text{продукты}) - \\sum \\nu_i C_{p,i}(\\text{реагенты})', 'изменение теплоемкости в реакции'],
    ['physics', 'C_p = a + bT + cT^{-2}', 'температурная зависимость теплоемкости кирхгоф'],
    ['physics', 'S = k_B \\ln W', 'энтропия больцмана термодинамическая вероятность'],
    ['physics', '\\lim_{T \\to 0} S = 0', 'третье начало термодинамики нулевая энтропия при 0к'],
    ['physics', 'S^\\circ = \\int_0^T \\frac{C_p}{T} dT', 'абсолютная энтропия через теплоемкость'],
    ['physics', '\\ln\\frac{p_2}{p_1} = \\frac{\\Delta H_{\\text{исп}}}{R} \\left( \\frac{1}{T_1} - \\frac{1}{T_2} \\right)', 'уравнение клаузиуса-клапейрона испарение'],
    ['physics', '\\frac{d \\ln p}{dT} = \\frac{\\Delta H}{RT^2}', 'уравнение клаузиуса-клапейрона дифференциальная форма'],
    ['physics', '\\Delta G = -RT \\ln \\frac{p_{\\text{равн}}}{p^\\circ}', 'энергия гиббса через равновесное давление'],
    ['physics', '\\mu_i = \\mu_i^\\circ + RT \\ln a_i', 'химический потенциал через активность'],
    ['physics', 'a_i = \\gamma_i x_i', 'активность через коэффициент активности и мольную долю'],
    ['physics', '\\mu_i = \\mu_i^\\circ + RT \\ln f_i + RT \\ln p_i', 'химический потенциал в газовой фазе'],
    ['physics', 'RT \\ln \\gamma_i = \\Delta \\mu_i^{\\text{изб}}', 'избыточный химический потенциал коэффициент активности'],
    ['physics', '\\ln \\gamma_i = \\varepsilon_i^j x_j', 'коэффициент активности в разбавленном растворе'],
    ['physics', '\\Delta G^{\\text{изб}} = RT \\sum x_i \\ln \\gamma_i', 'избыточная энергия гиббса раствора'],
    ['physics', 'G_E = \\Delta G_{\\text{реал}} - \\Delta G_{\\text{идеал}}', 'избыточная энергия гиббса реальный раствор'],
    ['physics', 'H_E = \\Delta H_{\\text{реал}} - \\Delta H_{\\text{идеал}}', 'избыточная энтальпия смешения'],
    ['physics', 'S_E = \\Delta S_{\\text{реал}} - \\Delta S_{\\text{идеал}}', 'избыточная энтропия смешения'],
    ['physics', 'G_E = x_1 x_2 \\sum_{i=0}^n L_i(x_1 - x_2)^i', 'полином редлиха-кистера избыточная энергия'],
    ['physics', 'G_E = x_1 x_2 \\left( L_0 + L_1(x_1 - x_2) + L_2(x_1 - x_2)^2 \\right)', 'модель редлиха-кистера-панджа'],
    ['physics', 'G_E = RT \\left( x_1 \\ln \\gamma_1 + x_2 \\ln \\gamma_2 \\right)', 'избыточная энергия гиббса через коэффициенты активности'],
    ['physics', '\\ln \\gamma_1 = \\frac{\\Omega}{RT} x_2^2', 'регулярный раствор параметр взаимодействия'],
    ['physics', '\\Delta G_{\\text{см}} = \\Delta H_{\\text{см}} - T\\Delta S_{\\text{см}}', 'энергия гиббса смешения'],
    ['physics', '\\sigma = \\sigma_p + K \\left( \\frac{l}{d} - 1 \\right)', 'прочность композита коэффициент неравноосности зерна отношение длины к диаметру'],
    ['physics', '\\tau_{\\text{св}} = \\frac{\\sigma_{в} \\cdot d}{2l}', 'прочность связи на границе раздела волокно матрица напряжение растяжения диаметр длина'],
    ['physics', '\\varepsilon_B = \\varepsilon_M = \\varepsilon_K', 'условие совместной деформации деформация волокна матрицы композита'],
    ['physics', '\\sigma_k = \\sigma_B V_B + \\sigma_M (1 - V_B)', 'предел прочности композита закон аддитивности объёмная доля волокон'],
    ['physics', '\\sigma_B = \\frac{1}{d \\cdot 2\\pi}', 'разрушение волокна при пластическом течении матрицы длина диаметр'],
    ['physics', '\\cos \\theta^\\circ = \\frac{\\sigma_{\\text{П}} - \\sigma_{\\text{ТК}}}{\\sigma_{\\text{ТК}}}', 'закон Юнга краевой угол поверхностное натяжение смачивание'],
    ['physics', 'V = K \\cdot \\exp\\left(-\\frac{E}{f \\cdot R \\cdot T}\\right)', 'скорость растекания расплава линия смачивания энергия активации'],
    ['physics', 'j_{\\text{пр}} = \\frac{K \\cdot T \\cdot A^*}{h \\cdot A_{\\text{пр}}} \\cdot \\exp\\left(-\\frac{E_{\\text{пр}}}{KT}\\right)', 'прямой поток атомов жидкой фазы смачивание адсорбция'],
    ['physics', 'j_{\\text{обр}} = \\frac{K \\cdot T \\cdot A^*}{h \\cdot A_{\\text{обр}}} \\cdot \\exp\\left(-\\frac{E_{\\text{обр}}}{KT}\\right)', 'обратный поток атомов десорбция'],
    ['physics', '\\Delta G = \\sigma_{\\text{жт}}(\\cos Q^\\circ - \\cos Q_g)', 'движущая сила растекания свободная поверхностная энергия краевой угол'],
    ['physics', '\\cos Q < (\\alpha - Q) \\cdot \\cos \\alpha / \\sin(\\alpha - Q)', 'условие капиллярного течения по канавке волокон'],
    ['physics', 'r_1 = \\frac{3}{4} \\left( \\psi \\frac{\\Delta G \\cdot m}{\\eta \\cdot \\rho \\cdot a} \\right)^{\\frac{1}{3}} \\cdot \\tau^{\\frac{1}{3}}', 'кинетика линейного растекания расплава по волокнам'],
    ['physics', 'E = \\frac{R(\\ln V_2 - \\ln V_1)}{T_2 - T_1} \\, T_1 \\cdot T_2', 'энергия активации скорость процесса температура'],
    ['physics', 'D = D_0 \\cdot \\exp\\left(-\\frac{E}{RT}\\right)', 'коэффициент диффузии температура энергия активации'],
    ['physics', '\\tau = \\frac{X^2}{4D}', 'время диффузии ширина зоны коэффициент диффузии'],
    ['physics', 'm = S_{\\text{об}} / F', 'масса металла удельная площадь растекания препрег'],
    ['physics', 'V_1 = nI(X^2 + 2r_pX)', 'объём переходной зоны композит'],
    ['physics', 'N = V_f \\cdot r_{\\text{обр}}^2 / r_f^2', 'количество волокон в образце объёмная доля радиус'],
    ['physics', 'M_{\\text{Ме}} = (1 - V_f) \\cdot V_{\\text{обр}} \\cdot \\rho_{\\text{Ме}} \\cdot K', 'масса металла объём образца плотность'],
    ['physics', 'X_1 = r_f \\sqrt{\\frac{(1 - V_f) \\cdot K \\cdot \\rho_{\\text{Ме}}}{h V_f \\cdot \\rho_{\\text{МеС}}}}}', 'ширина переходной зоны TiC межфазная граница сплав волокно'],
    ['physics', 'C = \\frac{2X_1 r_f + X_1^2}{2X_2 r_f + X_2^2}', 'объёмная доля карбида титана в переходной зоне'],
    ['physics', 'W_A = \\sigma_{\\text{жт}} (\\cos Q + 1)', 'работа адгезии смачивание межфазное натяжение краевой угол'],
    ['physics', '\\cos Q^o = \\frac{W_A - \\sigma_{\\text{жт}}}{\\sigma_{\\text{жт}}}', 'равновесный краевой угол работа адгезии'],
    ['physics', 'W_A = 2\\sigma_{\\text{жт}}', 'полное смачивание работа адгезии межфазное натяжение'],
    ['math', 'r = \\sqrt[3]{\\frac{3c}{4\\pi\\rho}}', 'радиус сферической частицы концентрация плотность'],
    ['math', 'l = \\sqrt[3]{\\frac{c}{\\rho}}', 'ребро куба частицы концентрация плотность'],
    ['math', 'd = cx / (\\rho - c)', 'размер частицы кубическая упаковка пустоты'],
    ['physics', '\\ln(I_0/I_n) = \\tau l', 'оптическая плотность мутность закон Бугера Ламберта Бера'],
    ['physics', 'D = k \\lambda^{-n}', 'оптическая плотность длина волны Геллер'],
    ['physics', '\\tau = \\kappa \\lambda^{-m}', 'мутность длина волны показатель рассеяния'],
    ['physics', '\\Delta = \\sqrt{2D\\tau}', 'закон Эйнштейна Смолуховского среднеквадратичное смещение броуновское движение'],
    ['physics', 'D = \\frac{kT}{6\\pi\\eta r}', 'коэффициент диффузии сферическая частица вязкость радиус'],
    ['physics', '\\ln \\frac{V_h}{V_0} = \\frac{V(\\rho - \\rho_0)gh}{kT}', 'гипсометрический закон Лапласа седиментационное равновесие распределение частиц по высоте'],
    ['physics', 'K_{\\text{сед}} = \\frac{9\\eta}{2r^2(\\rho - \\rho_0)}', 'константа седиментации кинетическая устойчивость'],
    ['physics', 'h_e = \\frac{kT}{V(\\rho - \\rho_0)g}', 'гипсометрическая высота седиментационно диффузионное равновесие'],
    ['physics', 'u = \\frac{2g(\\rho - \\rho_0)r^2}{9\\eta_0}', 'скорость седиментации частицы сила тяжести вязкость'],
    ['physics', 'r = \\sqrt{\\frac{9\\eta_0 u}{2g(\\rho - \\rho_0)}}', 'радиус частицы из скорости седиментации'],
    ['math', 'm = m_i + (dm/d\\tau)\\tau_i', 'уравнение касательной кривой седиментации'],
    ['physics', 'U_{\\text{int}} = \\Delta U_2 - \\Delta U_0', 'энергия взаимодействия частиц дисперсная система'],
    ['physics', 'F = \\eta S \\frac{dv}{dx}', 'закон Ньютона вязкость сила трения градиент скорости'],
    ['physics', 'V = \\frac{\\pi r^4 P}{8\\eta l} t', 'уравнение Пуазейля расход жидкости капилляр вязкость'],
    ['physics', '\\eta = \\eta_0 (1 + \\alpha \\varphi)', 'уравнение Эйнштейна вязкость дисперсной системы объемная доля форма частиц'],
    ['physics', 'V = \\frac{2 \\cdot \\pi \\cdot R \\cdot A}{P \\cdot l}', 'скорость износа радиус площадь поперечного сечения нагрузка дистанция'],
    ['math', 'f(x) = a_0 + a_1x + a_2x^2 + a_3x^3', 'полином регрессия коэффициенты кубический'],
    ['math', 'Y = a_0 + a_1x^1 + a_2x^2 + a_3x^3', 'уравнение регрессии полином третьей степени'],
    ['math', 'r_{ab} = \\frac{\\text{cov}(a, b)}{\\sqrt{S_a^2 \\cdot S_b^2}}', 'коэффициент корреляции ковариация дисперсия'],
    ['math', '\\text{cov}(a, b) = M(a \\cdot b) - M(a) \\cdot M(b)', 'ковариация математическое ожидание'],
    ['math', 'M(a) = \\frac{1}{n} \\sum a_i', 'математическое ожидание среднее арифметическое'],
    ['physics', 'l_f > 250 \\, d_f > l_{\\text{кр}}', 'критическая длина волокна диаметр армирование'],
    ['physics', '\\sigma_{\\text{км}} = \\sigma_f V_f + \\sigma_{m,\\text{ф}} \\cdot V_m', 'предел прочности композит волокно матрица объемная доля'],
    ['physics', 'V_m = 1 - V_f', 'объемная доля матрицы'],
    ['physics', 'S = d_f \\cdot l_f \\cdot n', 'площадь волокон диаметр длина число'],
    ['physics', 'V_f = \\frac{S}{F_{\\text{иссл пов ин}}}', 'объемная доля волокон площадь поверхность'],
    ['physics', 'S_l = d_f \\cdot l_f \\cdot n_1', 'площадь волокон фиксированной длины'],
    ['physics', 'S_f = S_l / F', 'поверхностная доля волокон площадь исследуемая площадь'],
    ['physics', 'S_f = \\sum_{i=1}^{k} S_{fi}', 'суммарная поверхность волокон всех длин'],
    ['physics', '\\sigma_f = \\sigma_f \\left( 1 - (1 - \\beta) \\frac{l_{\\text{кр}}}{l} \\right)', 'предел прочности волокна коэффициент передачи нагрузки критическая длина'],
    ['physics', '\\sigma_B^{\\text{lb}} = \\sigma_B^{\\text{утв}} V_{fl} \\left( 1 - (1 - \\beta) \\frac{l_{\\text{кр}}}{l_i} \\right) + (\\sigma_m)_{\\text{ef}} \\cdot V_{mfi}', 'временное сопротивление композита прочность волокна объемная доля матрица'],
    ['math', '\\frac{\\partial U}{\\partial t} = L^2 \\left( \\frac{\\partial^2 U}{\\partial x^2} + \\frac{\\partial^2 U}{\\partial y^2} + \\frac{\\partial^2 U}{\\partial z^2} \\right)', 'оператор Лапласа теплопроводность диффузия уравнение в частных производных'],
    ['text', 'H8/d9, H9/d9, H11/d11, H7/e8, H8/e8, H7/f7, H7/g6', 'посадка система отверстия допуск предпочтительная'],
    ['text', 'H7/h6, H8/h7, H8/h8, H11/h11', 'посадка система отверстия допуск'],
    ['text', 'F8/h6, H7/h6, H8/h7, H8/h8, H11/h11', 'посадка система вала допуск'],
    ['text', 'H8/d9', 'посадка предпочтительная зазор'],
    ['text', 'H9/d9', 'посадка предпочтительная зазор'],
    ['text', 'H11/d11', 'посадка предпочтительная зазор'],
    ['text', 'H7/e8', 'посадка предпочтительная зазор'],
    ['text', 'H7/h6', 'посадка предпочтительная переходная'],
    ['text', 'F8/h6', 'посадка система вала'],
    ['text', 'ГОСТ 2.101-68', 'стандарт виды изделий конструкторская документация'],
    ['text', 'ГОСТ 2.102-68', 'стандарт виды комплектности конструкторских документов'],
    ['text', 'ГОСТ 2.104-2006', 'стандарт основные надписи чертежи'],
    ['text', 'ГОСТ 2.106-96', 'стандарт текстовые документы спецификация'],
    ['text', 'ГОСТ 2.108-68', 'стандарт спецификация чертежи'],
    ['text', 'ГОСТ 2.109-73', 'стандарт рабочие чертежи деталей'],
    ['text', 'ГОСТ 2.113-75', 'стандарт групповые документы'],
    ['text', 'ГОСТ 2.114-95', 'стандарт технические условия'],
    ['text', 'ГОСТ 2.301-68', 'стандарт форматы чертежей'],
    ['text', 'ГОСТ 2.303-68', 'стандарт линии чертежа'],
    ['text', 'ГОСТ 2.304-81', 'стандарт шрифты чертёжные'],
    ['text', 'ГОСТ 2.305-2008', 'стандарт изображения виды разрезы сечения'],
    ['text', 'ГОСТ 2.306-68', 'стандарт графические обозначения материалов'],
    ['text', 'ГОСТ 2.308-79', 'стандарт шероховатость поверхностей'],
    ['text', 'ГОСТ 2.309-73', 'стандарт покрытия термическая обработка'],
    ['text', 'ГОСТ 2.310-68', 'стандарт маркировка клеймение'],
    ['text', 'ГОСТ 2.311-68', 'стандарт резьба'],
    ['text', 'ГОСТ 2.312-72', 'стандарт сварные швы'],
    ['text', 'ГОСТ 2.313-82', 'стандарт паяные и клеёные соединения'],
    ['text', 'ГОСТ 2.314-68', 'стандарт технические требования'],
    ['text', '15Х', 'сталь легированная хромистая'],
    ['text', '20Х', 'сталь легированная хромистая'],
    ['text', '30Х', 'сталь легированная хромистая'],
    ['text', '38ХА', 'сталь легированная высококачественная хромистая'],
    ['text', '40ХН', 'сталь легированная хромоникелевая'],
    ['text', '20ХН3А', 'сталь легированная хромоникелевая высококачественная'],
    ['text', '12ХН3А', 'сталь легированная хромоникелевая высококачественная'],
    ['text', '18ХГТ', 'сталь легированная хромомарганцовистая титаносодержащая'],
    ['text', '25ХГСА', 'сталь легированная хромомарганцевокремнистая высококачественная'],
    ['text', '30ХГСА', 'сталь легированная хромомарганцевокремнистая высококачественная'],
    ['text', 'ШХ15', 'сталь подшипниковая хромистая'],
    ['text', '9ХС', 'сталь инструментальная легированная хромокремнистая'],
    ['text', 'Х12М', 'сталь инструментальная штамповая хромомолибденовая'],
    ['text', 'Р6АМ5', 'сталь быстрорежущая вольфрамомолибденовая'],
    ['text', 'Р9М4К8', 'сталь быстрорежущая кобальтовая'],
    ['text', 'СЧ10', 'серый чугун предел прочности 100 мпа'],
    ['text', 'СЧ15', 'серый чугун предел прочности 150 мпа'],
    ['text', 'СЧ20', 'серый чугун предел прочности 200 мпа'],
    ['text', 'СЧ25', 'серый чугун предел прочности 250 мпа'],
    ['text', 'ВЧ35', 'высокопрочный чугун предел прочности 350 мпа'],
    ['text', 'ВЧ40', 'высокопрочный чугун предел прочности 400 мпа'],
    ['text', 'ВЧ45', 'высокопрочный чугун предел прочности 450 мпа'],
    ['text', 'ВЧ50', 'высокопрочный чугун предел прочности 500 мпа'],
    ['text', 'КЧ30-6', 'ковкий чугун прочность 300 мпа относительное удлинение 6%'],
    ['text', 'КЧ35-10', 'ковкий чугун прочность 350 мпа удлинение 10%'],
    ['text', 'КЧ45-7', 'ковкий чугун прочность 450 мпа удлинение 7%'],
    ['text', 'ЧН15Д7', 'чугун никелевый медьсодержащий'],
    ['text', 'ЧХ28', 'чугун хромистый высоколегированный'],
    ['text', 'АД0', 'алюминий технический особой чистоты'],
    ['text', 'АД1', 'алюминий технический высокой чистоты'],
    ['text', 'АМг2', 'алюминиевый сплав магний'],
    ['text', 'АМг5', 'алюминиевый сплав магний'],
    ['text', 'АМг6', 'алюминиевый сплав магний высокопрочный'],
    ['text', 'Д16', 'дюралюминий алюминий медь магний марганец'],
    ['text', 'Д1', 'дюралюминий алюминий медь магний'],
    ['text', 'В95', 'алюминиевый сплав высокопрочный цинк магний медь'],
    ['text', 'АК8', 'алюминиевый сплав ковочный'],
    ['text', 'АЛ19', 'алюминиевый сплав литейный'],
    ['text', 'ВТ1-0', 'технический титан высокой чистоты'],
    ['text', 'ВТ1-00', 'технический титан особой чистоты'],
    ['text', 'ВТ3-1', 'титановый сплав легированный алюминием хромом молибденом'],
    ['text', 'ВТ5', 'титановый сплав легированный алюминием'],
    ['text', 'ВТ5-1', 'титановый сплав легированный алюминием оловом'],
    ['text', 'ВТ14', 'титановый сплав легированный алюминием молибденом ванадием'],
    ['text', 'ВТ16', 'титановый сплав легированный алюминием молибденом ванадием хромом'],
    ['text', 'ОТ4-1', 'титановый сплав легированный алюминием марганцем'],
    ['text', 'М1', 'медь техническая чистота 99.9%'],
    ['text', 'М2', 'медь техническая чистота 99.7%'],
    ['text', 'М3', 'медь техническая чистота 99.5%'],
    ['text', 'Л90', 'томпак латунь 90% меди 10% цинка'],
    ['text', 'Л68', 'латунь 68% меди 32% цинка'],
    ['text', 'ЛС64-2', 'латунь свинец 64% меди 2% свинца'],
    ['text', 'БрО10Ф1', 'бронза олово фосфор'],
    ['text', 'БрА7', 'бронза алюминий 7% алюминия'],
    ['text', 'БрКН1-3', 'бронза кремний никель'],
    ['text', 'УПИ 1/2', 'угловой шов прерывистый катет 1мм шаг 2мм'],
    ['text', 'Т1-Δ4', 'тавровый шов двусторонний прерывистый шахматный катет 4мм'],
    ['text', 'Н1-Δ8', 'нахлёсточный шов прерывистый катет 8мм'],
    ['text', 'С2-ø6', 'стыковой шов на остающейся подкладке диаметр 6мм'],
    ['text', 'У4-12', 'угловой шов четырёхсторонний катет 12мм'],
    ['text', 'M24x1.5LH', 'метрическая резьба левая шаг 1.5мм диаметр 24мм'],
    ['text', 'Tr32x6P3', 'трапецеидальная резьба многозаходная ход 6мм шаг 3мм'],
    ['text', 'S16x2', 'упорная резьба диаметр 16мм шаг 2мм'],
    ['text', 'Rd40', 'круглая резьба диаметр 40мм'],
    ['text', 'M40x3-6H', 'метрическая резьба поле допуска 6h'],
    ['text', 'M20-7H/7g6g', 'метрическая резьба комбинированное поле допуска'],
    ['text', 'Закалка+отпуск', 'термическая обработка улучшение'],
    ['text', 'Закалка ТВЧ', 'термическая обработка закалка токами высокой частоты поверхностная'],
    ['text', 'Нормализация+отпуск', 'термическая обработка нормализация с последующим отпуском'],
    ['text', 'Отжиг рекристаллизационный', 'термическая обработка снятие наклёпа'],
    ['text', 'Старение искусственное', 'термическая обработка дисперсионное твердение'],
    ['text', 'Цементация+закалка', 'химико-термическая обработка науглероживание и закалка'],
    ['text', '100% контроль', 'контроль качества сплошной'],
    ['text', 'Выборочный контроль 10%', 'контроль качества выборочный статистический'],
    ['text', 'Контроль ВИК', 'контроль качества визуальный измерительный'],
    ['text', 'Контроль ОТК', 'отдел технического контроля качество продукции'],
    ['text', 'Партия №__', 'маркировка партии продукции'],
    ['text', 'Серийный номер', 'идентификационный номер изделия'],
    ['text', 'HRC', 'твёрдость по роквеллу шкала с'],
    ['text', 'HRB', 'твёрдость по роквеллу шкала в'],
    ['text', 'HV', 'твёрдость по виккерсу'],
    ['text', 'HB', 'твёрдость по бринеллю'],
    ['text', 'HSD', 'твёрдость по шору'],
    ['text', 'Т1-Δ5', 'сварной шов тавровый двусторонний прерывистый'],
    ['text', 'У4', 'сварной шов угловой односторонний'],
    ['text', 'Н1-Δ8', 'сварной шов нахлесточный прерывистый'],
    ['text', 'С2', 'сварной шов стыковой односторонний'],
    ['text', 'Т3-Δ10', 'сварной шов тавровый односторонний'],
    ['text', 'Закалка', 'термическая обработка мартенситное превращение'],
    ['text', 'Отпуск', 'термическая обработка снятие напряжений'],
    ['text', 'Нормализация', 'термическая обработка гомогенизация структуры'],
    ['text', 'Отжиг', 'термическая обработка рекристаллизация'],
    ['text', 'Старение', 'термическая обработка выделение упрочняющих фаз'],
    ['text', 'Цементация', 'химико-термическая обработка науглероживание'],
    ['text', 'Азотирование', 'химико-термическая обработка насыщение азотом'],
    ['text', 'Цианирование', 'химико-термическая обработка насыщение углеродом и азотом'],
    ['text', 'Борирование', 'химико-термическая обработка насыщение бором'],
    ['text', '10', 'сталь углеродистая качественная конструкционная'],
    ['text', '20', 'сталь углеродистая качественная'],
    ['text', '35', 'сталь углеродистая качественная'],
    ['text', '40', 'сталь углеродистая качественная'],
    ['text', '45', 'сталь углеродистая качественная'],
    ['text', '50', 'сталь углеродистая качественная'],
    ['text', '60', 'сталь углеродистая качественная'],
    ['text', 'У8', 'сталь инструментальная углеродистая'],
    ['text', 'У12', 'сталь инструментальная углеродистая'],
    ['text', '9ХС', 'сталь инструментальная легированная хром кремний'],
    ['text', 'ХВГ', 'сталь инструментальная хром вольфрам марганец'],
    ['text', 'Р18', 'сталь быстрорежущая вольфрам'],
    ['text', 'Р9', 'сталь быстрорежущая вольфрам'],
    ['text', '20Х13', 'сталь коррозионностойкая'],
    ['text', '30Х13', 'сталь коррозионностойкая'],
    ['text', '40Х13', 'сталь коррозионностойкая'],
    ['text', '95Х18', 'сталь коррозионностойкая'],
    ['text', 'ХН45Ю', 'сплав жаропрочный хром никель алюминий'],
    ['text', 'ХН70Ю', 'сплав жаропрочный нихром'],
    ['text', 'ЭИ654', 'сплав жаропрочный марка'],
    ['text', 'ЭП718', 'сплав жаропрочный марка'],
    ['text', 'ВЖ98', 'сплав жаропрочный литейный'],
    ['text', 'АК4', 'алюминиевый сплав ковочный'],
    ['text', 'АК6', 'алюминиевый сплав ковочный'],
    ['text', 'АЛ2', 'алюминиевый сплав литейный'],
    ['text', 'АЛ9', 'алюминиевый сплав литейный'],
    ['text', 'МА2', 'магниевый сплав'],
    ['text', 'МА8', 'магниевый сплав'],
    ['text', 'ЛС59-1', 'латунь свинец'],
    ['text', 'ЛЖМц59-1-1', 'латунь железо марганец'],
    ['text', 'БрА10Ж3Мц2', 'бронза алюминий железо марганец'],
    ['text', 'БрКМц3-1', 'бронза кремний марганец'],
    ['text', 'БрБ2', 'бронза бериллиевая'],
    ['text', 'ВК3', 'твердый сплав вольфрам кобальт'],
    ['text', 'ВК15', 'твердый сплав вольфрам кобальт'],
    ['text', 'ВК20', 'твердый сплав вольфрам кобальт'],
    ['text', 'Т5К10', 'твердый сплав титан вольфрам кобальт'],
    ['text', 'Т14К8', 'твердый сплав титан вольфрам кобальт'],
    ['text', 'Т30К4', 'твердый сплав титан вольфрам кобальт'],
    ['text', 'ВТ6', 'титановый сплав'],
    ['text', 'ВТ8', 'титановый сплав'],
    ['text', 'ОТ4', 'титановый сплав'],
    ['text', 'ГОСТ 2.105-95', 'стандарт оформления текстовых документов'],
    ['text', 'ГОСТ 2.109-73', 'стандарт рабочих чертежей'],
    ['text', 'ГОСТ 2.311-68', 'стандарт изображения резьбы'],
    ['text', 'ГОСТ 2.302-68', 'стандарт масштабов'],
    ['text', 'ГОСТ 2.307-68', 'стандарт нанесения размеров'],
    ['text', 'ГОСТ 8.051-81', 'стандарт погрешностей измерений'],
    ['text', 'M10x0.75', 'метрическая резьба мелкий шаг'],
    ['text', 'M12x1.25', 'метрическая резьба шаг'],
    ['text', 'Tr40x7', 'трапецеидальная резьба многозаходная'],
    ['text', 'S20x2', 'упорная резьба'],
    ['text', 'Rc 3/4"', 'коническая резьба внутренняя'],
    ['text', 'Rp 1"', 'цилиндрическая резьба трубная'],
    ['text', 'M20x1.5LH', 'левая метрическая резьба'],
    ['text', 'H11/f6', 'посадка комбинированная система отверстия зазор'],
    ['text', 'H12/b11', 'посадка грубая большой зазор'],
    ['text', 'E9/h8', 'посадка система вала зазор'],
    ['text', 'F8/h6', 'посадка скольжения'],
    ['text', 'K8/h7', 'посадка переходная'],
    ['text', 'P9/h8', 'посадка с натягом легкая'],
    ['text', 'U8/h7', 'посадка с натягом тяжелая'],
    ['text', 'Ra 0.08', 'шероховатость высший класс чистоты'],
    ['text', 'Ra 0.16', 'шероховатость высокий класс'],
    ['text', 'Ra 0.63', 'шероховатость средний класс'],
    ['text', 'Rz 20', 'шероховатость высота неровностей'],
    ['text', 'Rmax 100', 'максимальная высота неровностей'],
    ['text', 'Горячая прокатка', 'обработка металлов давлением температура рекристаллизации'],
    ['text', 'Холодная прокатка', 'обработка металлов давлением наклеп'],
    ['text', 'Штамповка', 'обработка металлов давлением объемная'],
    ['text', 'Вытяжка', 'листоштамповка'],
    ['text', 'Гибка', 'листоштамповка пластическая деформация'],
    ['text', 'Волочение', 'обработка металлов давлением пруток проволока'],
    ['text', 'Прессование', 'экструзия металлов'],
    ['text', 'УЗК', 'ультразвуковой контроль дефектоскопия'],
    ['text', 'РК', 'радиографический контроль сварные швы'],
    ['text', 'МПД', 'магнитопорошковый метод контроль трещин'],
    ['text', 'Капиллярный контроль', 'дефектоскопия пенетрант'],
    ['text', 'ТВЧ', 'термическая обработка токами высокой частоты'],
    ['text', 'ППД', 'поверхностно пластическое деформирование упрочнение'],
    ['text', 'Двутавр 20', 'прокатный профиль балка'],
    ['text', 'Швеллер 12', 'прокатный профиль'],
    ['text', 'Уголок 50x5', 'прокатный профиль угол равнополочный'],
    ['text', 'Уголок 63x40x6', 'прокатный профиль угол неравнополочный'],
    ['text', 'Круг 30', 'прокатный профиль круглый'],
    ['text', 'Квадрат 20', 'прокатный профиль квадратный'],
    ['text', 'H6/f5', 'посадка система отверстия зазор'],
    ['text', 'H7/e7', 'посадка система отверстия зазор'],
    ['text', 'H8/e8', 'посадка система отверстия зазор'],
    ['text', 'H9/e9', 'посадка система отверстия зазор'],
    ['text', 'H10/d10', 'посадка система отверстия зазор'],
    ['text', 'H11/d11', 'посадка система отверстия зазор'],
    ['text', 'H12/d12', 'посадка система отверстия зазор'],
    ['text', 'H6/js5', 'посадка переходная система отверстия'],
    ['text', 'H7/js6', 'посадка переходная система отверстия'],
    ['text', 'H8/js7', 'посадка переходная система отверстия'],
    ['text', 'H6/k5', 'посадка переходная система отверстия'],
    ['text', 'H7/k6', 'посадка переходная система отверстия'],
    ['text', 'H8/k7', 'посадка переходная система отверстия'],
    ['text', 'H7/m6', 'посадка переходная система отверстия'],
    ['text', 'H8/m7', 'посадка переходная система отверстия'],
    ['text', 'H7/n6', 'посадка переходная система отверстия'],
    ['text', 'H7/p6', 'посадка натяг система отверстия'],
    ['text', 'H7/r6', 'посадка натяг система отверстия'],
    ['text', 'H8/s7', 'посадка натяг система отверстия'],
    ['text', 'H7/t6', 'посадка натяг система отверстия'],
    ['text', 'H7/u7', 'посадка натяг система отверстия'],
    ['text', 'H8/x8', 'посадка натяг система отверстия'],
    ['text', 'F7/h6', 'посадка система вала зазор'],
    ['text', 'F8/h7', 'посадка система вала зазор'],
    ['text', 'G7/h6', 'посадка система вала зазор'],
    ['text', 'H8/h7', 'посадка система вала зазор'],
    ['text', 'J6/h5', 'посадка система вала зазор'],
    ['text', 'Js6/h5', 'посадка переходная система вала'],
    ['text', 'Js7/h6', 'посадка переходная система вала'],
    ['text', 'K7/h6', 'посадка переходная система вала'],
    ['text', 'M7/h6', 'посадка переходная система вала'],
    ['text', 'N7/h6', 'посадка переходная система вала'],
    ['text', 'P7/h6', 'посадка натяг система вала'],
    ['text', 'R7/h6', 'посадка натяг система вала'],
    ['text', 'S7/h6', 'посадка натяг система вала'],
    ['text', 'T7/h6', 'посадка натяг система вала'],
    ['text', 'U7/h6', 'посадка натяг система вала'],
    ['text', 'Ст3', 'сталь углеродистая обыкновенного качества'],
    ['text', 'Ст5', 'сталь углеродистая обыкновенного качества'],
    ['text', '08Х18Н10Т', 'сталь нержавеющая хром никель титан'],
    ['text', '12Х18Н10Т', 'сталь нержавеющая аустенитная'],
    ['text', '20Х13', 'сталь коррозионностойкая мартенситная'],
    ['text', '40Х', 'сталь легированная хром'],
    ['text', '45', 'сталь углеродистая качественная'],
    ['text', '65Г', 'сталь пружинная марганец'],
    ['text', 'У7', 'сталь инструментальная углеродистая'],
    ['text', 'У10', 'сталь инструментальная углеродистая'],
    ['text', 'Р6М5', 'сталь быстрорежущая вольфрам молибден'],
    ['text', 'ВК6', 'твердый сплав вольфрам кобальт'],
    ['text', 'ВК8', 'твердый сплав вольфрам кобальт'],
    ['text', 'Т15К6', 'твердый сплав титан вольфрам кобальт'],
    ['text', 'Д16Т', 'алюминиевый сплав дюралюминий термически обработанный'],
    ['text', 'АМг3', 'алюминиевый сплав магний'],
    ['text', 'АМц', 'алюминиевый сплав марганец'],
    ['text', 'Л63', 'латунь медь цинк'],
    ['text', 'БрА9Ж4', 'бронза алюминий железо'],
    ['text', 'БрОЦ4-3', 'бронза олово цинк свинец'],
    ['text', 'Ra 0.32', 'шероховатость среднеарифметическое отклонение'],
    ['text', 'Ra 1.25', 'шероховатость среднеарифметическое отклонение'],
    ['text', 'Rz 40', 'шероховатость высота неровностей'],
    ['text', 'Rz 80', 'шероховатость высота неровностей'],
    ['text', 'IT5', 'квалитет точность допуск'],
    ['text', 'IT6', 'квалитет точность допуск'],
    ['text', 'IT7', 'квалитет точность допуск'],
    ['text', 'IT8', 'квалитет точность допуск'],
    ['text', 'IT9', 'квалитет точность допуск'],
    ['text', 'IT10', 'квалитет точность допуск'],
    ['text', 'M10x1.5', 'метрическая резьба шаг'],
    ['text', 'M16x2', 'метрическая резьба шаг'],
    ['text', 'Tr20x4', 'трапецеидальная резьба'],
    ['text', 'G 1/2"', 'трубная цилиндрическая резьба'],
    ['text', 'ⓘ 0.05', 'допуск цилиндричности'],
    ['text', '∥ 0.02', 'допуск параллельности'],
    ['text', '⟂ 0.03', 'допуск перпендикулярности'],
    ['text', '⌒ 0.04', 'допуск круглости'],
    ['text', '/○/ 0.01', 'допуск соосности'],
]

df = pd.DataFrame(data, columns=['class', 'latex_code', 'context'])

features = ColumnTransformer([
    ('context_vec', Pipeline([
        ('tfidf', TfidfVectorizer(ngram_range=(1, 2), max_features=5000)),
        ('svd', TruncatedSVD(n_components=100))  # Уменьшаем размерность
    ]), 'context'),

    ('formula_char', TfidfVectorizer(ngram_range=(2, 5), analyzer='char_wb', max_features=2000), 'latex_code'),
    ('formula_word', TfidfVectorizer(ngram_range=(1, 2), max_features=500), 'latex_code'),
])

model = Pipeline([
    ('features', features),
    ('classifier', LogisticRegression(class_weight='balanced', C=1.0))
])

model.fit(df[['latex_code', 'context']], df['class'])
joblib.dump(model, 'formula_classifier.pkl')
print("✅ Модель переобучена")
